import { FAQItem } from '../types';
import { EduSection, educationalSections } from './education';

export type Language = 'en' | 'ms' | 'zh' | 'ta';

export const LANG_LABELS: Record<Language, string> = {
  en: 'English (EN)',
  ms: 'Bahasa Melayu (MS)',
  zh: '中文 (ZH)',
  ta: 'தமிழ் (TA)',
};

export const UI_TRANSLATIONS: Record<Language, Record<string, string>> = {
  en: {
    // Top Bar & Greetings
    health: 'Health',
    hub: 'Hub',
    active_user: 'Active User',
    chas_blue: 'CHAS Blue Member',
    action_recommended: 'Action Recommended',
    
    // Home Screen Referral Card
    fh_referral_title: 'FH Genetic Testing Referral',
    fh_referral_desc: 'Based on your recent cholesterol results, your doctor recommends FH genetic testing to better understand your condition.',
    recommended_next_step: 'Recommended Next Step',
    book_counselling_step: 'Book your pre-test counselling appointment.',
    next_appointment: 'Next Appointment',
    learn_why: 'Learn Why',
    why_referred_btn: 'Why Referred?',
    book_now_btn: 'Book Now',
    manage_slot_btn: 'Manage Slot',
    your_journey: 'YOUR JOURNEY',
    step_referral: 'Referral',
    step_counselling: 'Book Counselling',
    step_testing: 'Genetic Testing',
    
    // Quick Links
    quick_links: 'Quick Links',
    edit: 'Edit',
    link_appointments: 'Appointments',
    link_learn: 'Learn & Info',
    link_subsidies: 'Subsidies',
    link_care_team: 'Care Team',
    link_call: 'Direct Call',
    link_faqs: 'FAQs',
    
    // Care Team Card
    your_care_team: 'YOUR CARE TEAM',
    specialist_role: 'Senior Genetic Counsellor',
    specialist_hospital: 'National University Hospital',
    
    // Referral Details Screen
    referral_details_title: 'Referral Details',
    why_am_i_referred_title: 'Why am I referred for FH genetic testing?',
    explanation_1: 'Your lipid panel indicates extremely high LDL (bad) cholesterol levels. FH is a hereditary condition, meaning lifestyle alone is not the cause.',
    explanation_2: 'Genetic testing confirms if a specific gene variation is responsible. It helps your clinician custom-tailor highly effective preventative treatments for you and your family.',
    govt_subsidies_title: 'Government Subsidies',
    subsidies_desc: 'Up to 75% MOH subsidy for CHAS Blue / Pioneer Generation. MediSave can also be used for remaining co-payment.',
    what_should_i_do: 'What should I do now?',
    what_should_i_do_desc: 'We strongly recommend booking your 45-minute pre-test counselling. The session carries no obligation and explains all medical implications clearly.',
    book_counselling_session: 'Book Counselling Session',
    
    // Learn Screen
    education_hub_title: 'Genetic Education Hub',
    tab_guides: 'Videos & Guides',
    tab_checklist: 'Pre-Test Checklist',
    tab_faqs: 'Questions & Answers',
    
    // Booking Screen
    select_clinic_title: 'Select Hospital Clinic',
    search_placeholder: 'Search for hospital or location...',
    use_gps: 'Use My Live GPS',
    gps_calculating: 'Detecting live location...',
    available_slots: 'Available Slots',
    review_booking_title: 'Review Appointment Details',
    confirm_booking_btn: 'Confirm Booking',
    appointment_confirmed_title: 'Appointment Confirmed!',
    booking_success_desc: 'Your genetic counselling slot is locked. An SMS and Push notification have been scheduled.',
    add_to_calendar: 'Add to Calendar',
    reschedule_slot: 'Reschedule Slot',
    back_to_home: 'Back to Home',
    
    // Settings Screen
    settings_title: 'Settings',
    settings_desc: 'Configure how and when you receive genetic testing referrals and appointment alerts.',
    active_reminders: 'Active FH Reminders',
    active_reminders_desc: 'Receive educational updates and countdown reminders.',
    notification_channel: 'Notification Channel',
    reminder_frequency: 'Reminder Frequency',
    frequency_desc: 'Adjust how far in advance your reminder schedule triggers leading up to the appointment date.',
    freq_comprehensive: 'Comprehensive',
    freq_standard: 'Standard',
    freq_minimal: 'Minimal',
    freq_comprehensive_desc: 'Comprehensive: Sends alerts 1 month, 2 weeks, 1 week, and 1 day before your scheduled session.',
    freq_standard_desc: 'Standard: Sends alerts 1 week and 1 day before your scheduled session.',
    freq_minimal_desc: 'Minimal: Sends a single alert 1 day before your scheduled session.',
    active_schedule: 'Active Schedule',
    active_freq_comprehensive: 'Reminder 1 month, 2 weeks, 1 week, & 1 day before',
    active_freq_standard: 'Reminder 1 week & 1 day before',
    active_freq_minimal: 'Reminder 1 day before only',
    lang_pref_title: 'Language Preferences',
    lang_pref_desc: 'Select your preferred language. This updates all text content dynamically to ensure accessibility.',
    select_app_language: 'Select App Language',
    
    // Journey Screen
    progress_journey_title: 'My Patient Journey',
    status_unbooked: 'Counselling Booking Required',
    status_booked: 'Appointment Scheduled',
    status_confirmed: 'Attendance Confirmed',
    unbooked_journey_desc: 'Your active cardiac genetic referral requires you to schedule a counselling session.',
    timeline_title: 'Interactive Referral Timeline',
    
    // Common Action elements
    back: 'Back',

    // New additions for full translation support
    lab_reports_btn: 'Lab reports',
    med_reports_btn: 'Medical reports',
    med_refill_btn: 'Medication refill',
    payment_btn: 'Payment',
    health_profiles: 'Health Profiles',
    view_all_btn: 'View all',
    programmes_title: 'Programmes',
    referred_intro_title: 'Why Was I Referred?',
    referred_hi_lisa: 'Hi Lisa.',
    referred_doctor_rec: 'Your doctor has recommended genetic testing after reviewing your recent cholesterol results.',
    referred_means: "Here's what this means.",
    referred_why_doctor: 'Why your doctor referred you',
    referred_cholesterol_may_fh: 'Your recent cholesterol results suggest you may have Familial Hypercholesterolaemia (FH).',
    not_mean_have_fh: 'This does NOT mean you have FH.',
    genetic_testing_confirms: 'Genetic testing helps confirm whether FH is the cause.',
    referred_results_help_team: 'Your results help your healthcare team recommend the right care.',
    why_this_matters: 'Why this matters',
    early_diagnosis: 'Early diagnosis',
    early_diagnosis_desc: 'Start treatment sooner.',
    protect_family: 'Protect your family',
    protect_family_desc: 'FH can run in families.',
    personalized_care: 'Personalised care',
    personalized_care_desc: 'Results help guide your care.',
    what_happens_next: 'What happens next?',
    step_referral_received: 'Referral received',
    step_learn_about_fh: 'Learn about FH',
    step_current: 'Current',
    step_pre_test_counselling: 'Pre-test counselling',
    step_genetic_results: 'Genetic testing results',
    referred_next_step_learning: 'The next step is learning more about FH before attending your pre-test counselling appointment.',
    referred_before_app: 'Before your appointment',
    referred_spend_time: 'Spend just 2–3 minutes learning about FH before your counselling appointment.',
    referred_short_what_is: 'What is FH?',
    referred_short_why: 'Why testing?',
    referred_short_process: 'Testing process',
    referred_short_costs: 'Costs',
    referred_short_insurance: 'Insurance',
    referred_continue_learn: 'Continue to learn about FH before your appointment.',
    booking_secure_title: 'Secure Appointment Booking',
    booking_confirmed_status: 'Your appointment is confirmed',
    booking_subsidized_slot: 'MOH Subsidized Slot',
    booking_care_clinic: 'Care Clinic:',
    booking_specialist: 'Specialist:',
    booking_scheduled_date: 'Scheduled Date:',
    booking_confirmed_time: 'Confirmed Time:',
    booking_session_duration: 'Session Duration:',
    booking_out_of_pocket: 'Out-of-pocket Cost:',
    booking_chas_subsidized: 'CHAS Subsidized',
    booking_add_device_calendar: 'Add to Device Calendar',
    booking_essential_prep: 'Essential Preparation Instructions',
    booking_prep_no_fasting: 'No Fasting Required: Eat and drink normally before your session.',
    booking_prep_id_verif: 'ID Verification: Bring your NRIC physical card or log in via Singpass.',
    booking_prep_checklist: 'Complete your Pre-counselling Checklist before your appointment',
    booking_view_checklist: 'View Pre-Appointment Checklist',
    booking_reschedule_slot: 'Reschedule Appointment Slot',
    booking_cancel_slot: 'Cancel Appointment Booking',
    booking_eligible_subsidies: 'Based on your clinical referral, you are eligible for up to 75% MOH subsidies at these registered institutions.',
    booking_nearest_tag: 'NEAREST',
    booking_select_counselling_slot: 'Select counselling slot',
    booking_choose_subsidized_slot: 'Choose your subsidized genetic counselling slot.',
    booking_select_month: 'Select Month',
    booking_reschedule_alert: 'Reschedule mode active: Select a new slot below.',
    booking_nric_verified: 'Ready & Registered • NRIC/Singpass pre-cleared for clinical intake.',
    booking_unverified_alert: 'Attendance is unverified. Tap on lockscreen push alerts or settings to confirm attendance.',
    booking_session_desc: '45-minute session to answer family worries and finalize testing.',
    booking_review_details: 'Review Appointment Details',
    booking_confirm_slot_btn: 'Confirm Booking',
    booking_add_calendar_success: 'Apple Calendar .ics event downloaded successfully!',
    profile_my_health_profile: 'My Health Profile',
    profile_singpass_linked: 'Singpass Linked',
    profile_moh_identity_cleared: 'MOH Identity Cleared',
    profile_personal_particulars: 'Personal Particulars',
    profile_full_name: 'Full Name:',
    profile_nric_fin: 'NRIC/FIN:',
    profile_dob: 'Date of Birth:',
    profile_nationality: 'Nationality:',
    profile_mobile_number: 'Mobile Number:',
    profile_email_address: 'Email Address:',
    profile_residential: 'Residential:',
    profile_clinical_metrics: 'Clinical Metrics & Risks',
    profile_blood_group: 'Blood Group:',
    profile_height_weight: 'Height / Weight:',
    profile_known_allergies: 'Known Allergies:',
    profile_none_declared: 'None Declared',
    profile_cholesterol_level: 'Cholesterol Level:',
    profile_elevated_risk: 'Elevated risk',
    profile_active_referral: 'Active Referral:',
    profile_referred_by: 'Referred by Specialist Cardiology',
    profile_subsidies_financing: 'Subsidies & Financing',
    profile_chas_blue_member: 'CHAS Blue Tier Member',
    profile_chas_subsidy_level: 'MOH Subsidy level capped at 75%',
    profile_chas_card_expiry: 'CHAS Card Expiry:',
    profile_medisave_account: 'MediSave Account:',
    profile_medisave_note: '*Outpatient genetic counselling and test panels are fully claimable under MOH MediSave rules.',
    profile_family_cardiac_history: 'Family Cardiac History',
    profile_family_history_desc: "Familial Hypercholesterolemia (FH) is passed down from parents. Knowing your family's history provides critical context for testing:",
    journey_my_patient_journey: 'My Patient Journey',
    journey_appointment_progress: 'Your Appointment Progress',
    journey_appointment_status: 'Appointment Status',
    journey_interactive_referral_timeline: 'Interactive Referral Timeline',
    journey_referral_received: 'Referral received',
    journey_referral_received_desc: 'Recommended by Clinical Cardiology Specialist on 12 Jul 2026.',
    journey_edu_completed: 'Education materials reviewed',
    journey_edu_completed_desc: 'Subsidies, clinical video, and FAQs completed on Singapore HealthHub.',
    journey_slot_booked: 'Counselling slot booked',
    journey_slot_booked_desc: 'Successfully scheduled for {date} @ {time} at NUH Genetic Clinic.',
    journey_slot_action_needed: 'Action needed: Choose your subsidized genetic counselling slot.',
    journey_attend_counselling: 'Attend genetic counselling',
    journey_receive_results: 'Receive genetic results',
    journey_receive_results_desc: 'Discussion of preventative steps and tailored medicine 4 weeks after blood drawn.',
    lock_healthhub_preview: 'HealthHub App Lockscreen Preview',
    lock_just_now: 'Just Now',
    lock_counselling_reminder: 'Counselling Appointment Reminder',
    lock_counselling_confirmed_msg: 'Your genetic counselling is confirmed for {date} at {time}. Tap to complete checklist.',
    lock_counselling_tap_confirm_msg: 'Confirm your FH Genetic Counselling on {date} @ {time}.',
    lock_trigger_push_alert: 'Trigger Simulated Push Alert',
    lock_confirm_attendance_btn: 'Confirm Attendance',
    lock_reschedule_btn: 'Reschedule',
    lock_read_prep_btn: 'Read Prep Guide',
    lock_tap_confirm_db_msg: 'Tap "Confirm Attendance" to log your confirmation instantly in Singapore HealthHub database.',
    lock_swipe_hint: 'Swipe up to open registered credentials',
    profile_female_age: 'Female • 36',
    profile_full_name_val: 'Lisa Ho Siew Lan',
    profile_dob_val: '14 August 1989 (36 yrs)',
    profile_nationality_val: 'Singapore Citizen',
    profile_residential_val: 'Blk 451 Ang Mo Kio Ave 10, #08-122, Singapore 560451',
    profile_blood_group_val: 'O Rh+ (Positive)',
    profile_height_weight_val: '162 cm / 54 kg (BMI 20.6)',
    profile_cholesterol_level_val: 'LDL 5.4 mmol/L (Elevated risk)',
    profile_active_referral_val: 'FH Genetic Testing',
    profile_referred_by_val: 'Referred by Specialist Cardiology',
    profile_card_expiry_val: '31 Dec 2028',
    profile_father_history: 'Father (Diagnosed Age 48):',
    profile_father_history_desc: 'Coronary Heart Disease (Angioplasty & Stent)',
    profile_grandfather_history: 'Paternal Grandfather (Deceased Age 52):',
    profile_grandfather_history_desc: 'Fatal Myocardial Infarction (Acute Heart Attack)',
    profile_aunt_history: 'Paternal Aunt:',
    profile_aunt_history_desc: 'Severely high cholesterol (treated with Statins)',
    profile_mother_history: 'Mother & Siblings:',
    profile_mother_history_desc: 'No early history of heart disease declared',
    profile_care_coordination: 'Care Coordination',
    profile_primary_clinic_val: 'Ang Mo Kio Polyclinic',
    profile_referred_clinic_val: 'NUH Genetic Clinic',
    profile_emergency_contact_val: 'Ho Chin Teck',
    profile_relationship_no_val: 'Spouse • 9876 5432',
    profile_privacy_statement: "Your genetic profile data is fully protected under Singapore's national privacy laws and the Life Insurance Association (LIA) Moratorium. Your details will never be shared without your explicit consent.",
    settings_option_sms_only: 'SMS Messages Only (+65 9123 4567)',
    settings_option_push_only: 'HealthHub App Push Notifications',
    settings_option_both: 'Both SMS & App Push (Recommended)',
    settings_help_sms: 'Reminders will be sent directly via SMS text message to your registered mobile number.',
    settings_help_push: 'Reminders will appear on your lockscreen from the HealthHub app.',
    settings_help_both: 'Our system sends alerts to both SMS and App Push channels, ensuring older adults avoid missing referrals.',
    settings_freq_monthly: 'Monthly Info (Educational resources)',
    settings_freq_2_weeks: '2 Weeks Before (Initial nudge)',
    settings_freq_1_week: '1 Week Before (Highly protective)',
    settings_freq_1_day: '1 Day Before (Final preparation check)',
    settings_sms_preview_title: 'SMS Broadcast Preview',
    settings_sms_verified_sender: 'Verified MOH Sender',
    settings_lockscreen_preview_title: 'HealthHub App Lockscreen Preview',
    settings_lockscreen_header: 'HealthHub Singapore • Just Now',
    settings_sms_prefix: 'MOH HealthHub: Hi Lisa, your FH Genetic Counselling slot at National University Hospital Genetic Clinic is confirmed on {date} at {time}. Subsidies up to 75% are cleared. Bring Singpass. Info: https://hh.gov.sg/fh-ref',
    journey_prep_title: 'Preparation Checklist',
    journey_prep_desc: 'Make sure you know what to expect and what family history reports to bring. Review our guides.',
    journey_review_checklist_btn: 'Review checklist now',
    lockscreen_telco: 'Singapore Telecommunications',
    lockscreen_date: 'Wednesday, July 15, 2026',
    lockscreen_days_left: '7 Days Left',
    lockscreen_push_msg: 'Your genetic counselling is confirmed for {date} at {time}. Tap to complete checklist.',
    lockscreen_tap_confirm_info: 'Tap "Confirm Attendance" to log your confirmation instantly in Singapore HealthHub database.',
    lockscreen_swipe_hint: 'Swipe up to open registered credentials',
    booking_subsidies_computed: 'MOH Subsidies automatically computed via your linked Singpass status.',
    booking_no_slots_alert: 'No slots available on this date. Please select a highlighted day on the calendar above.',
    booking_assigned_specialist: 'Assigned Clinical Specialist',
    booking_address_label: 'Address:',
    booking_date_label: 'Date:',
    booking_time_label: 'Time:',
    booking_duration_label: 'Session Duration:',
    booking_out_of_pocket_label: 'Total Estimated Out-of-pocket Cost:',
    // Bottom Navigation Bar
    nav_home: 'Home',
    nav_learn: 'Learn',
    nav_book: 'Book',
    nav_journey: 'Journey',
    nav_profile: 'Profile',
    // Home Page Profiles
    home_profile_lisa: 'LISA HO',
    home_profile_spouse: 'HO CHIN TECK',
    // Home Page Programmes
    prog_active_hub: 'Active Hub',
    prog_diabetes_title: 'Diabetes Hub',
    prog_diabetes_desc: 'Personalized guides for managing and preventing diabetes.',
    prog_resource: 'Resource',
    prog_mental_title: 'Mental Well-being',
    prog_mental_desc: 'Mindfulness guides and support networks for emotional safety.',
    // Book Screen Selector Buttons
    booking_close_selector_btn: 'Close Selector',
    booking_change_estate_btn: 'Change Estate / GPS',
    // Clinic Names & Addresses
    clinic_nuh_name: 'National University Hospital Genetic Clinic',
    clinic_nuh_address: '5 Lower Kent Ridge Rd, Main Building Zone B, Singapore 119074',
    clinic_sgh_name: 'Singapore General Hospital Genetics Service',
    clinic_sgh_address: 'Outram Rd, Academic Medicine Basement 1, Singapore 169608',
    clinic_ttsh_name: 'Tan Tock Seng Hospital Clinical Genomics',
    clinic_ttsh_address: '11 Jalan Tan Tock Seng, Clinic 4B, Singapore 308433',
    clinic_kkh_name: "KK Women's and Children's Hospital Genetics Clinic",
    clinic_kkh_address: "100 Bukit Timah Rd, Children's Tower Level 5, Singapore 229899",
    // Doctors
    doc_helen_lim: 'Dr. Helen Lim',
    doc_albert_chiang: 'Dr. Albert Chiang',
    doc_marcus_goh: 'Dr. Marcus Goh',
    doc_fiona_lee: 'Dr. Fiona Lee',
    doc_benjamin_chew: 'Dr. Benjamin Chew',
    doc_sarah_tan: 'Dr. Sarah Tan',
    doc_claire_wong: 'Dr. Claire Wong',
    doc_jeanette_tan: 'Dr. Jeanette Tan',
    // Specialist Roles
    role_senior_genetic_counsellor: 'Senior Genetic Counsellor',
    role_consultant_cardiogeneticist: 'Consultant Cardiogeneticist',
    role_principal_genetics_specialist: 'Principal Genetics Specialist',
    role_senior_clinical_geneticist: 'Senior Clinical Geneticist',
    role_consultant_paediatric_geneticist: 'Consultant Paediatric Geneticist',
    role_lead_paediatric_counsellor: 'Lead Paediatric Counsellor',
    role_consultant_geneticist: 'Consultant Geneticist',
  },
  ms: {
    health: 'Health',
    hub: 'Hub',
    active_user: 'Pengguna Aktif',
    chas_blue: 'Ahli Biru CHAS',
    action_recommended: 'Tindakan Disyorkan',
    
    fh_referral_title: 'Rujukan Ujian Genetik FH',
    fh_referral_desc: 'Berdasarkan keputusan kolesterol anda baru-baru ini, doktor anda mengesyorkan ujian genetik FH untuk memahami keadaan anda dengan lebih baik.',
    recommended_next_step: 'Langkah Seterusnya Sila Ambil',
    book_counselling_step: 'Tempah janji temu kaunseling pra-ujian anda.',
    next_appointment: 'Janji Temu Seterusnya',
    learn_why: 'Ketahui Sebabnya',
    why_referred_btn: 'Kenapa Dirujuk?',
    book_now_btn: 'Tempah Sekarang',
    manage_slot_btn: 'Urus Slot',
    your_journey: 'PERJALANAN ANDA',
    step_referral: 'Rujukan',
    step_counselling: 'Tempah Kaunseling',
    step_testing: 'Ujian Genetik',
    
    quick_links: 'Pautan Pantas',
    edit: 'Edit',
    link_appointments: 'Janji Temu',
    link_learn: 'Belajar & Info',
    link_subsidies: 'Subsidi',
    link_care_team: 'Pasukan Penjagaan',
    link_call: 'Panggilan Terus',
    link_faqs: 'Soalan Lazim',
    
    your_care_team: 'PASUKAN PENJAGAAN ANDA',
    specialist_role: 'Kaunselor Genetik Kanan',
    specialist_hospital: 'National University Hospital',
    
    referral_details_title: 'Butiran Rujukan',
    why_am_i_referred_title: 'Mengapa saya dirujuk untuk ujian genetik FH?',
    explanation_1: 'Profil lipid anda menunjukkan tahap kolesterol LDL (buruk) yang sangat tinggi. FH adalah keadaan keturunan, bermakna gaya hidup sahaja bukanlah puncanya.',
    explanation_2: 'Ujian genetik mengesahkan jika variasi gen tertentu bertanggungjawab. Ia membantu pakar klinikal anda menyesuaikan rawatan pencegahan yang sangat berkesan untuk anda dan keluarga.',
    govt_subsidies_title: 'Subsidi Kerajaan',
    subsidies_desc: 'Subsidi MOH sehingga 75% untuk ahli CHAS Biru / Generasi Pioneer. MediSave juga boleh digunakan untuk baki pembayaran bersama.',
    what_should_i_do: 'Apakah yang perlu saya lakukan sekarang?',
    what_should_i_do_desc: 'Kami amat mengesyorkan anda menempah sesi kaunseling pra-ujian selama 45 minit. Sesi ini tiada sebarang kewajipan dan menerangkan implikasi perubatan dengan jelas.',
    book_counselling_session: 'Tempah Sesi Kaunseling',
    
    education_hub_title: 'Hab Pendidikan Genetik',
    tab_guides: 'Video & Panduan',
    tab_checklist: 'Senarai Semak',
    tab_faqs: 'Soalan & Jawapan',
    
    select_clinic_title: 'Pilih Klinik Hospital',
    search_placeholder: 'Cari hospital atau lokasi...',
    use_gps: 'Gunakan GPS Saya',
    gps_calculating: 'Mengesan lokasi semasa...',
    available_slots: 'Slot yang Tersedia',
    review_booking_title: 'Semak Butiran Janji Temu',
    confirm_booking_btn: 'Sahkan Tempahan',
    appointment_confirmed_title: 'Janji Temu Disahkan!',
    booking_success_desc: 'Slot kaunseling genetik anda telah ditempah. SMS dan pemberitahuan Push telah dijadualkan.',
    add_to_calendar: 'Tambah ke Kalendar',
    reschedule_slot: 'Penjadualan Semula',
    back_to_home: 'Kembali ke Laman Utama',
    
    settings_title: 'Tetapan',
    settings_desc: 'Konfigurasikan bagaimana dan bila anda menerima rujukan ujian genetik dan makluman janji temu.',
    active_reminders: 'Peringatan Aktif FH',
    active_reminders_desc: 'Terima kemas kini pendidikan dan peringatan undur.',
    notification_channel: 'Saluran Pemberitahuan',
    reminder_frequency: 'Kekerapan Peringatan',
    frequency_desc: 'Laraskan berapa hari lebih awal jadual peringatan anda diaktifkan menjelang tarikh janji temu.',
    freq_comprehensive: 'Komprehensif',
    freq_standard: 'Standard',
    freq_minimal: 'Minimal',
    freq_comprehensive_desc: 'Komprehensif: Menghantar makluman 1 bulan, 2 minggu, 1 minggu, dan 1 hari sebelum sesi janji temu anda.',
    freq_standard_desc: 'Standard: Menghantar makluman 1 minggu dan 1 hari sebelum sesi janji temu anda.',
    freq_minimal_desc: 'Minimal: Menghantar makluman tunggal 1 hari sebelum sesi janji temu anda.',
    active_schedule: 'Jadual Aktif',
    active_freq_comprehensive: 'Peringatan 1 bulan, 2 minggu, 1 minggu, & 1 hari sebelum',
    active_freq_standard: 'Peringatan 1 minggu & 1 hari sebelum',
    active_freq_minimal: 'Peringatan 1 hari sebelum sahaja',
    lang_pref_title: 'Tetapan Bahasa',
    lang_pref_desc: 'Pilih bahasa kegemaran anda. Ini mengemas kini semua kandungan teks secara dinamik untuk komuniti Singapura.',
    select_app_language: 'Pilih Bahasa Aplikasi',
    
    progress_journey_title: 'Perjalanan Pesakit Saya',
    status_unbooked: 'Pendaftaran Kaunseling Diperlukan',
    status_booked: 'Janji Temu Dijadualkan',
    status_confirmed: 'Kehadiran Disahkan',
    unbooked_journey_desc: 'Rujukan genetik kardio aktif anda memerlukan anda menjadualkan sesi kaunseling.',
    timeline_title: 'Garis Masa Rujukan Interaktif',
    
    back: 'Kembali',

    // New additions for full translation support
    lab_reports_btn: 'Laporan makmal',
    med_reports_btn: 'Laporan perubatan',
    med_refill_btn: 'Isi semula ubat',
    payment_btn: 'Bayaran',
    health_profiles: 'Profil Kesihatan',
    view_all_btn: 'Lihat semua',
    programmes_title: 'Program',
    referred_intro_title: 'Kenapa Saya Dirujuk?',
    referred_hi_lisa: 'Hai Lisa.',
    referred_doctor_rec: 'Doktor anda telah mengesyorkan ujian genetik selepas menyemak keputusan kolesterol anda baru-baru ini.',
    referred_means: 'Inilah maksud perkara ini.',
    referred_why_doctor: 'Sebab doktor merujuk anda',
    referred_cholesterol_may_fh: 'Keputusan kolesterol baru-baru ini menunjukkan anda mungkin mempunyai Familial Hypercholesterolaemia (FH).',
    not_mean_have_fh: 'Ini BUKAN bermakna anda menghidap FH.',
    genetic_testing_confirms: 'Ujian genetik membantu mengesahkan sama ada FH adalah puncanya.',
    referred_results_help_team: 'Keputusan anda membantu pasukan penjagaan kesihatan anda mengesyorkan penjagaan yang betul.',
    why_this_matters: 'Mengapa ini penting',
    early_diagnosis: 'Diagnosis awal',
    early_diagnosis_desc: 'Mulakan rawatan lebih awal.',
    protect_family: 'Lindungi keluarga anda',
    protect_family_desc: 'FH boleh diwarisi dalam keluarga.',
    personalized_care: 'Penjagaan peribadi',
    personalized_care_desc: 'Keputusan membantu membimbing penjagaan anda.',
    what_happens_next: 'Apakah yang berlaku seterusnya?',
    step_referral_received: 'Rujukan diterima',
    step_learn_about_fh: 'Ketahui tentang FH',
    step_current: 'Semasa',
    step_pre_test_counselling: 'Kaunseling pra-ujian',
    step_genetic_results: 'Keputusan ujian genetik',
    referred_next_step_learning: 'Langkah seterusnya ialah mengetahui lebih lanjut tentang FH sebelum menghadiri janji temu kaunseling pra-ujian anda.',
    referred_before_app: 'Sebelum janji temu anda',
    referred_spend_time: 'Luangkan masa 2-3 minit untuk mengetahui tentang FH sebelum janji temu kaunseling anda.',
    referred_short_what_is: 'Apakah itu FH?',
    referred_short_why: 'Kenapa ujian?',
    referred_short_process: 'Proses ujian',
    referred_short_costs: 'Kos',
    referred_short_insurance: 'Insurans',
    referred_continue_learn: 'Teruskan belajar tentang FH sebelum janji temu anda.',
    booking_secure_title: 'Tempahan Janji Temu Selamat',
    booking_confirmed_status: 'Janji temu anda telah disahkan',
    booking_subsidized_slot: 'Slot Subsidi MOH',
    booking_care_clinic: 'Klinik Penjagaan:',
    booking_specialist: 'Pakar:',
    booking_scheduled_date: 'Tarikh Dijadualkan:',
    booking_confirmed_time: 'Masa Disahkan:',
    booking_session_duration: 'Tempoh Sesi:',
    booking_out_of_pocket: 'Kos Sendiri:',
    booking_chas_subsidized: 'Disubsidi CHAS',
    booking_add_device_calendar: 'Tambah ke Kalendar Peranti',
    booking_essential_prep: 'Arahan Penyediaan Penting',
    booking_prep_no_fasting: 'Tidak Perlu Berpuasa: Makan dan minum secara normal sebelum sesi anda.',
    booking_prep_id_verif: 'Pengesahan ID: Bawa kad fizikal NRIC anda atau log masuk melalui Singpass.',
    booking_prep_checklist: 'Lengkapkan Senarai Semak Pra-kaunseling sebelum janji temu anda',
    booking_view_checklist: 'Lihat Senarai Semak Pra-Janji Temu',
    booking_reschedule_slot: 'Penjadualan Semula Slot Janji Temu',
    booking_cancel_slot: 'Batalkan Tempahan Janji Temu',
    booking_eligible_subsidies: 'Berdasarkan rujukan klinikal anda, anda layak mendapat subsidi MOH sehingga 75% di institusi berdaftar ini.',
    booking_nearest_tag: 'TERDEKAT',
    booking_select_counselling_slot: 'Pilih slot kaunseling',
    booking_choose_subsidized_slot: 'Pilih slot kaunseling genetik bersubsidi anda.',
    booking_select_month: 'Pilih Bulan',
    booking_reschedule_alert: 'Mod penjadualan semula aktif: Pilih slot baharu di bawah.',
    booking_nric_verified: 'Sedia & Berdaftar • NRIC/Singpass pra-dibersihkan untuk kemasukan klinikal.',
    booking_unverified_alert: 'Kehadiran tidak disahkan. Ketik pada makluman tolak skrin kunci atau tetapan untuk mengesahkan kehadiran.',
    booking_session_desc: 'Sesi 45 minit untuk menjawab kebimbangan keluarga dan memuktamadkan ujian.',
    booking_review_details: 'Semak Butiran Janji Temu',
    booking_confirm_slot_btn: 'Sahkan Tempahan',
    booking_add_calendar_success: 'Acara kalendar Apple .ics berjaya dimuat turun!',
    profile_my_health_profile: 'Profil Kesihatan Saya',
    profile_singpass_linked: 'Singpass Dipautkan',
    profile_moh_identity_cleared: 'Identiti MOH Dibersihkan',
    profile_personal_particulars: 'Butiran Peribadi',
    profile_full_name: 'Nama Penuh:',
    profile_nric_fin: 'NRIC/FIN:',
    profile_dob: 'Tarikh Lahir:',
    profile_nationality: 'Kewarganegaraan:',
    profile_mobile_number: 'Nombor Telefon Bimbit:',
    profile_email_address: 'Alamat E-mel:',
    profile_residential: 'Kediaman:',
    profile_clinical_metrics: 'Metrik Klinikal & Risiko',
    profile_blood_group: 'Kumpulan Darah:',
    profile_height_weight: 'Tinggi / Berat:',
    profile_known_allergies: 'Alergi Diketahui:',
    profile_none_declared: 'Tiada Diisytiharkan',
    profile_cholesterol_level: 'Tahap Kolesterol:',
    profile_elevated_risk: 'Risiko meningkat',
    profile_active_referral: 'Rujukan Aktif:',
    profile_referred_by: 'Dirujuk oleh Kardiologi Pakar',
    profile_subsidies_financing: 'Subsidi & Pembiayaan',
    profile_chas_blue_member: 'Ahli CHAS Blue Tier',
    profile_chas_subsidy_level: 'Tahap subsidi MOH dihadkan pada 75%',
    profile_chas_card_expiry: 'Tamat Tempoh Kad CHAS:',
    profile_medisave_account: 'Akaun MediSave:',
    profile_medisave_note: '*Kaunseling genetik pesakit luar dan panel ujian boleh dituntut sepenuhnya di bawah peraturan MediSave MOH.',
    profile_family_cardiac_history: 'Sejarah Jantung Keluarga',
    profile_family_history_desc: 'Familial Hypercholesterolemia (FH) diwarisi daripada ibu bapa. Mengetahui sejarah keluarga anda memberikan konteks kritikal untuk ujian:',
    journey_my_patient_journey: 'Perjalanan Pesakit Saya',
    journey_appointment_progress: 'Kemajuan Janji Temu Anda',
    journey_appointment_status: 'Status Janji Temu',
    journey_interactive_referral_timeline: 'Garis Masa Rujukan Interaktif',
    journey_referral_received: 'Rujukan diterima',
    journey_referral_received_desc: 'Disyorkan oleh Pakar Kardiologi Klinikal pada 12 Jul 2026.',
    journey_edu_completed: 'Bahan pendidikan disemak',
    journey_edu_completed_desc: 'Subsidi, video klinikal, dan FAQ selesai di HealthHub Singapura.',
    journey_slot_booked: 'Slot kaunseling ditempah',
    journey_slot_booked_desc: 'Berjaya dijadualkan untuk {date} @ {time} di Klinik Genetik NUH.',
    journey_slot_action_needed: 'Tindakan diperlukan: Pilih slot kaunseling genetik bersubsidi anda.',
    journey_attend_counselling: 'Hadir ke kaunseling genetik',
    journey_receive_results: 'Terima keputusan genetik',
    journey_receive_results_desc: 'Perbincangan langkah-langkah pencegahan dan rawatan tersuai 4 minggu selepas darah diambil.',
    lock_healthhub_preview: 'Pratonton Skrin Kunci Aplikasi HealthHub',
    lock_just_now: 'Baru Sahaja',
    lock_counselling_reminder: 'Peringatan Janji Temu Kaunseling',
    lock_counselling_confirmed_msg: 'Kaunseling genetik anda telah disahkan untuk {date} pada {time}. Ketik untuk melengkapkan senarai semak.',
    lock_counselling_tap_confirm_msg: 'Sahkan Kaunseling Genetik FH anda pada {date} @ {time}.',
    lock_trigger_push_alert: 'Cetuskan Amaran Simpanan Tolak Simpanan',
    lock_confirm_attendance_btn: 'Sahkan Kehadiran',
    lock_reschedule_btn: 'Penjadualan Semula',
    lock_read_prep_btn: 'Baca Panduan Persediaan',
    lock_tap_confirm_db_msg: 'Ketik "Sahkan Kehadiran" untuk mendaftarkan pengesahan anda serta-merta dalam pangkalan data HealthHub Singapura.',
    lock_swipe_hint: 'Slaid ke atas untuk membuka bukti kelayakan berdaftar',
    profile_female_age: 'Perempuan • 36',
    profile_full_name_val: 'Lisa Ho Siew Lan',
    profile_dob_val: '14 Ogos 1989 (36 thn)',
    profile_nationality_val: 'Warganegara Singapura',
    profile_residential_val: 'Blk 451 Ang Mo Kio Ave 10, #08-122, Singapura 560451',
    profile_blood_group_val: 'O Rh+ (Positif)',
    profile_height_weight_val: '162 cm / 54 kg (BMI 20.6)',
    profile_cholesterol_level_val: 'LDL 5.4 mmol/L (Risiko meningkat)',
    profile_active_referral_val: 'Ujian Genetik FH',
    profile_referred_by_val: 'Dirujuk oleh Kardiologi Pakar',
    profile_card_expiry_val: '31 Dis 2028',
    profile_father_history: 'Bapa (Didiagnosis Umur 48):',
    profile_father_history_desc: 'Penyakit Jantung Koronari (Angioplasti & Stent)',
    profile_grandfather_history: 'Datuk Sebelah Bapa (Meninggal Dunia Umur 52):',
    profile_grandfather_history_desc: 'Infarksi Miokardial Maut (Serangan Jantung Akut)',
    profile_aunt_history: 'Ibu Saudara Sebelah Bapa:',
    profile_aunt_history_desc: 'Kolesterol sangat tinggi (dirawat dengan Statin)',
    profile_mother_history: 'Ibu & Adik-beradik:',
    profile_mother_history_desc: 'Tiada sejarah awal penyakit jantung diisytiharkan',
    profile_care_coordination: 'Penyelarasan Penjagaan',
    profile_primary_clinic_val: 'Poliklinik Ang Mo Kio',
    profile_referred_clinic_val: 'Klinik Genetik NUH',
    profile_emergency_contact_val: 'Ho Chin Teck',
    profile_relationship_no_val: 'Pasangan • 9876 5432',
    profile_privacy_statement: 'Data profil genetik anda dilindungi sepenuhnya di bawah undang-undang privasi kebangsaan Singapura dan Moratorium Persatuan Insurans Hayat (LIA). Butiran anda tidak akan sekali-kali dikongsi tanpa persetujuan jelas anda.',
    settings_option_sms_only: 'Mesej SMS Sahaja (+65 9123 4567)',
    settings_option_push_only: 'Pemberitahuan Push Aplikasi HealthHub',
    settings_option_both: 'Kedua-dua SMS & Aplikasi Push (Disyorkan)',
    settings_help_sms: 'Peringatan akan dihantar terus melalui mesej teks SMS ke nombor mudah alih anda yang berdaftar.',
    settings_help_push: 'Peringatan akan dipaparkan pada skrin kunci anda daripada aplikasi HealthHub.',
    settings_help_both: 'Sistem kami menghantar makluman kepada kedua-dua saluran SMS dan Push Aplikasi, memastikan warga emas tidak terlepas rujukan.',
    settings_freq_monthly: 'Maklumat Bulanan (Bahan pendidikan)',
    settings_freq_2_weeks: '2 Minggu Sebelum (Dorongan awal)',
    settings_freq_1_week: '1 Minggu Sebelum (Sangat menyokong)',
    settings_freq_1_day: '1 Hari Sebelum (Pemeriksaan persediaan terakhir)',
    settings_sms_preview_title: 'Pratonton Siaran SMS',
    settings_sms_verified_sender: 'Penghantar MOH Disahkan',
    settings_lockscreen_preview_title: 'Pratonton Skrin Kunci Aplikasi HealthHub',
    settings_lockscreen_header: 'HealthHub Singapura • Baru Sahaja',
    settings_sms_prefix: 'MOH HealthHub: Hai Lisa, slot Kaunseling Genetik FH anda di Klinik Genetik Hospital Universiti Nasional disahkan pada {date} pukul {time}. Subsidi sehingga 75% telah diluluskan. Bawa Singpass. Info: https://hh.gov.sg/fh-ref',
    journey_prep_title: 'Senarai Semak Persediaan',
    journey_prep_desc: 'Pastikan anda mengetahui apa yang diharapkan dan laporan sejarah keluarga apa yang perlu dibawa. Semak panduan kami.',
    journey_review_checklist_btn: 'Semak senarai semak sekarang',
    lockscreen_telco: 'Singapore Telecommunications',
    lockscreen_date: 'Rabu, 15 Julai 2026',
    lockscreen_days_left: 'Tinggal 7 Hari',
    lockscreen_push_msg: 'Kaunseling genetik anda telah disahkan untuk {date} pukul {time}. Ketik untuk melengkapkan senarai semak.',
    lockscreen_tap_confirm_info: 'Ketik "Sahkan Kehadiran" untuk mendaftarkan pengesahan anda serta-merta dalam pangkalan data HealthHub Singapura.',
    lockscreen_swipe_hint: 'Slaid ke atas untuk membuka bukti kelayakan berdaftar',
    booking_subsidies_computed: 'Subsidi MOH dikira secara automatik melalui status Singpass anda yang dipautkan.',
    booking_no_slots_alert: 'Tiada slot tersedia pada tarikh ini. Sila pilih hari yang diserlahkan pada kalendar di atas.',
    booking_assigned_specialist: 'Pakar Klinikal yang Ditugaskan',
    booking_address_label: 'Alamat:',
    booking_date_label: 'Tarikh:',
    booking_time_label: 'Masa:',
    booking_duration_label: 'Tempoh Sesi:',
    booking_out_of_pocket_label: 'Jumlah Anggaran Kos Sendiri:',
    // Bottom Navigation Bar
    nav_home: 'Laman Utama',
    nav_learn: 'Belajar',
    nav_book: 'Tempah',
    nav_journey: 'Perjalanan',
    nav_profile: 'Profil',
    // Home Page Profiles
    home_profile_lisa: 'LISA HO',
    home_profile_spouse: 'HO CHIN TECK',
    // Home Page Programmes
    prog_active_hub: 'Hub Aktif',
    prog_diabetes_title: 'Hub Diabetes',
    prog_diabetes_desc: 'Panduan diperibadikan untuk mengurus dan mencegah diabetes.',
    prog_resource: 'Sumber',
    prog_mental_title: 'Kesejahteraan Mental',
    prog_mental_desc: 'Panduan kesedaran dan rangkaian sokongan untuk keselamatan emosi.',
    // Book Screen Selector Buttons
    booking_close_selector_btn: 'Tutup Pemilih',
    booking_change_estate_btn: 'Tukar Estet / GPS',
    // Clinic Names & Addresses
    clinic_nuh_name: 'Klinik Genetik Hospital Universiti Nasional',
    clinic_nuh_address: '5 Lower Kent Ridge Rd, Bangunan Utama Zon B, Singapura 119074',
    clinic_sgh_name: 'Perkhidmatan Genetik Hospital Umum Singapura',
    clinic_sgh_address: 'Outram Rd, Aras Bawah Perubatan Akademik 1, Singapura 169608',
    clinic_ttsh_name: 'Genomik Klinikal Hospital Tan Tock Seng',
    clinic_ttsh_address: '11 Jalan Tan Tock Seng, Klinik 4B, Singapura 308433',
    clinic_kkh_name: 'Klinik Genetik Hospital Wanita dan Kanak-kanak KK',
    clinic_kkh_address: '100 Bukit Timah Rd, Menara Kanak-kanak Aras 5, Singapura 229899',
    // Doctors
    doc_helen_lim: 'Dr. Helen Lim',
    doc_albert_chiang: 'Dr. Albert Chiang',
    doc_marcus_goh: 'Dr. Marcus Goh',
    doc_fiona_lee: 'Dr. Fiona Lee',
    doc_benjamin_chew: 'Dr. Benjamin Chew',
    doc_sarah_tan: 'Dr. Sarah Tan',
    doc_claire_wong: 'Dr. Claire Wong',
    doc_jeanette_tan: 'Dr. Jeanette Tan',
    // Specialist Roles
    role_senior_genetic_counsellor: 'Kaunselor Genetik Kanan',
    role_consultant_cardiogeneticist: 'Pakar Kardiogenetik Perunding',
    role_principal_genetics_specialist: 'Pakar Genetik Utama',
    role_senior_clinical_geneticist: 'Pakar Genetik Klinikal Kanan',
    role_consultant_paediatric_geneticist: 'Pakar Genetik Pediatrik Perunding',
    role_lead_paediatric_counsellor: 'Kaunselor Pediatrik Utama',
    role_consultant_geneticist: 'Pakar Genetik Perunding',
  },
  zh: {
    health: 'Health',
    hub: 'Hub',
    active_user: '活跃用户',
    chas_blue: 'CHAS蓝色社保卡会员',
    action_recommended: '建议采取行动',
    
    fh_referral_title: 'FH 基因检测转诊推荐',
    fh_referral_desc: '根据您最近的胆固醇检查结果，您的医生建议进行FH基因检测，以更好地了解您的健康状况。',
    recommended_next_step: '推荐下一步行动',
    book_counselling_step: '预约您的检测前基因咨询。',
    next_appointment: '下一次预约',
    learn_why: '了解原因',
    why_referred_btn: '为何被转诊？',
    book_now_btn: '立即预约',
    manage_slot_btn: '管理预约',
    your_journey: '您的康复之旅',
    step_referral: '转诊推荐',
    step_counselling: '预约咨询',
    step_testing: '基因检测',
    
    quick_links: '快速链接',
    edit: '编辑',
    link_appointments: '预约服务',
    link_learn: '科普与资讯',
    link_subsidies: '政府津贴',
    link_care_team: '医疗团队',
    link_call: '直接通话',
    link_faqs: '常见问题',
    
    your_care_team: '您的医疗团队',
    specialist_role: '高级基因咨询师',
    specialist_hospital: '国立大学医院 (NUH)',
    
    referral_details_title: '转诊详情',
    why_am_i_referred_title: '为什么我被推荐进行FH基因检测？',
    explanation_1: '您的血脂报告显示低密度脂蛋白（坏胆固醇）水平极高。FH是一种遗传性疾病，这意味着单靠改善生活方式无法完全解决。',
    explanation_2: '基因检测能确认是否存在特定的基因变异。这有助于您的临床医生为您和您的家人量身定制高效的预防性治疗方案。',
    govt_subsidies_title: '政府津贴与补助',
    subsidies_desc: 'CHAS蓝色卡和建国一代享有高达75%的卫生部 (MOH) 津贴。MediSave（保健储蓄）也可用来自付剩余的共付额。',
    what_should_i_do: '我现在应该做什么？',
    what_should_i_do_desc: '我们强烈建议您预约45分钟的免费检测前咨询。此咨询无强制检测义务，将为您清晰解答所有医学影响。',
    book_counselling_session: '预约基因咨询',
    
    education_hub_title: '基因科普中心',
    tab_guides: '视频与指南',
    tab_checklist: '准备清单',
    tab_faqs: '常见问答',
    
    select_clinic_title: '选择就诊医院',
    search_placeholder: '搜索医院或地点...',
    use_gps: '使用我的实时GPS位置',
    gps_calculating: '正在定位中...',
    available_slots: '可选预约时段',
    review_booking_title: '核对预约信息',
    confirm_booking_btn: '确认预约',
    appointment_confirmed_title: '预约已确认！',
    booking_success_desc: '您的基因咨询时段已锁定。我们已为您安排了短信和应用推送提醒。',
    add_to_calendar: '添加到日历',
    reschedule_slot: '重新安排预约',
    back_to_home: '返回主页',
    
    settings_title: '设置',
    settings_desc: '配置您接收基因检测转诊和预约提醒的方式和时间。',
    active_reminders: '启用 FH 转诊提醒',
    active_reminders_desc: '接收科普资讯和倒计时消息提醒。',
    notification_channel: '通知渠道',
    reminder_frequency: '提醒频率',
    frequency_desc: '调整在预约日期之前多久触发提醒通知。',
    freq_comprehensive: '全面提醒 (Comprehensive)',
    freq_standard: '标准提醒 (Standard)',
    freq_minimal: '极简提醒 (Minimal)',
    freq_comprehensive_desc: '全面提醒：在您预约时间前1个月、2周、1周及1天发送多次提醒，提供全面而贴心的保障。',
    freq_standard_desc: '标准提醒：在您预约时间前1周和1天发送关键提醒。',
    freq_minimal_desc: '极简提醒：仅在您预约时间前1天发送一次单次提醒。',
    active_schedule: '当前提醒计划',
    active_freq_comprehensive: '预约前1个月、2周、1周及1天提醒',
    active_freq_standard: '预约前1周及1天提醒',
    active_freq_minimal: '仅在预约前1天提醒',
    lang_pref_title: '语言偏好设置',
    lang_pref_desc: '选择您偏好的语言。此设置将实时更新所有文本内容，以支持新加坡的各个多元化社区。',
    select_app_language: '选择应用语言',
    
    progress_journey_title: '我的就医时间线',
    status_unbooked: '需要预约基因咨询',
    status_booked: '预约已安排',
    status_confirmed: '到场出席已确认',
    unbooked_journey_desc: '您目前有一项有效的心脏基因转诊，需要您安排一次咨询服务。',
    timeline_title: '转诊互动时间线',
    
    back: '返回',

    // New additions for full translation support
    lab_reports_btn: '化验报告',
    med_reports_btn: '医疗报告',
    med_refill_btn: '药物配给',
    payment_btn: '账单与付款',
    health_profiles: '健康档案',
    view_all_btn: '查看全部',
    programmes_title: '健康计划',
    referred_intro_title: '为什么我被推荐转诊？',
    referred_hi_lisa: '您好，Lisa。',
    referred_doctor_rec: '医生在查看了您最近的胆固醇检查结果后，建议您进行基因检测。',
    referred_means: '以下是这其中的含义。',
    referred_why_doctor: '医生推荐您转诊的原因',
    referred_cholesterol_may_fh: '您最近的胆固醇结果表明您可能患有家族性高胆固醇血症 (FH)。',
    not_mean_have_fh: '这并不意味着您一定患有 FH。',
    genetic_testing_confirms: '基因检测有助于确认 FH 是否是根本原因。',
    referred_results_help_team: '检测结果将协助您的医疗团队为您推荐最合适的治疗方案。',
    why_this_matters: '为什么这很重要',
    early_diagnosis: '早期诊断',
    early_diagnosis_desc: '尽早开始预防与治疗。',
    protect_family: '保护您的家人',
    protect_family_desc: 'FH 是一种可在家族中遗传的疾病。',
    personalized_care: '个性化医疗健康',
    personalized_care_desc: '检测结果将引导您的个性化护理。',
    what_happens_next: '接下来会发生什么？',
    step_referral_received: '已收到转诊推荐',
    step_learn_about_fh: '了解家族性高胆固醇血症 (FH)',
    step_current: '当前步骤',
    step_pre_test_counselling: '检测前咨询',
    step_genetic_results: '基因检测结果报告',
    referred_next_step_learning: '下一步行动是在参加检测前遗传学咨询之前，了解更多关于 FH 的科普知识。',
    referred_before_app: '预约就诊前准备',
    referred_spend_time: '在您参加咨询预约前，只需花 2-3 分钟了解 FH 即可。',
    referred_short_what_is: '什么是FH？',
    referred_short_why: '为何检测？',
    referred_short_process: '检测流程',
    referred_short_costs: '津贴与费用',
    referred_short_insurance: '保险权益',
    referred_continue_learn: '请在预约就诊前继续了解 FH 科普。',
    booking_secure_title: '安全预约服务',
    booking_confirmed_status: '您的预约已确认',
    booking_subsidized_slot: '卫生部 (MOH) 资助时段',
    booking_care_clinic: '就诊诊所：',
    booking_specialist: '医生专长：',
    booking_scheduled_date: '预约日期：',
    booking_confirmed_time: '确认时间：',
    booking_session_duration: '问诊时长：',
    booking_out_of_pocket: '个人自付费用：',
    booking_chas_subsidized: 'CHAS 资助',
    booking_add_device_calendar: '添加到手机日历',
    booking_essential_prep: '重要就诊准备说明',
    booking_prep_no_fasting: '无需空腹：问诊前可正常饮食。',
    booking_prep_id_verif: '身份验证：请携带您的身份证件 NRIC 或通过 Singpass 登录。',
    booking_prep_checklist: '请在就诊前在应用中完成您的“检测前咨询准备清单”',
    booking_view_checklist: '查看就诊前准备清单',
    booking_reschedule_slot: '重新安排预约时段',
    booking_cancel_slot: '取消预约就诊',
    booking_eligible_subsidies: '根据您的临床转诊推荐，您有资格在这些注册医疗机构享受高达 75% 的 MOH 转诊津贴。',
    booking_nearest_tag: '最近距离',
    booking_select_counselling_slot: '选择基因咨询时段',
    booking_choose_subsidized_slot: '选择您的政府资助基因咨询预约时段。',
    booking_select_month: '选择月份',
    booking_reschedule_alert: '重新预约模式已激活：请在下方选择一个新时段。',
    booking_nric_verified: '已就绪并登记 • NRIC/Singpass 临床入院前验证已通过。',
    booking_unverified_alert: '到场状态尚未验证。请点击锁屏推送或设置页面来确认您将按时出席。',
    booking_session_desc: '45分钟的专家问诊，为您解答家族担忧并最终确定检测细节。',
    booking_review_details: '核对预约细节',
    booking_confirm_slot_btn: '确认预约时段',
    booking_add_calendar_success: 'Apple日历 .ics 事件已成功下载！',
    profile_my_health_profile: '我的健康档案',
    profile_singpass_linked: 'Singpass 已联接',
    profile_moh_identity_cleared: '卫生部 MOH 身份验证已通过',
    profile_personal_particulars: '个人基本信息',
    profile_full_name: '姓名：',
    profile_nric_fin: '身份证号 / NRIC:',
    profile_dob: '出生日期：',
    profile_nationality: '国籍：',
    profile_mobile_number: '手机号码：',
    profile_email_address: '电子邮箱：',
    profile_residential: '家庭住址：',
    profile_clinical_metrics: '临床指标与健康风险',
    profile_blood_group: '血型：',
    profile_height_weight: '身高 / 体重：',
    profile_known_allergies: '已知过敏史：',
    profile_none_declared: '无已知过敏',
    profile_cholesterol_level: '胆固醇指标：',
    profile_elevated_risk: '偏高（存在风险）',
    profile_active_referral: '有效转诊推荐：',
    profile_referred_by: '由心脏专科门诊医生推荐',
    profile_subsidies_financing: '政府津贴与补助',
    profile_chas_blue_member: 'CHAS 蓝色社保卡会员',
    profile_chas_subsidy_level: '卫生部 MOH 津贴比例最高达 75%',
    profile_chas_card_expiry: 'CHAS 卡有效期至：',
    profile_medisave_account: '保健储蓄账户 (MediSave):',
    profile_medisave_note: '*门诊基因咨询和检测项目完全符合卫生部 MOH MediSave 报销规定。',
    profile_family_cardiac_history: '家族心脏病史',
    profile_family_history_desc: '家族性高胆固醇血症 (FH) 会在家族中遗传。了解您的家族病史可为基因检测提供极其关键的医学上下文背景：',
    journey_my_patient_journey: '我的就医时间线',
    journey_appointment_progress: '您的就诊进度条',
    journey_appointment_status: '就诊状态',
    journey_interactive_referral_timeline: '转诊互动时间线',
    journey_referral_received: '已收到转诊推荐',
    journey_referral_received_desc: '于 2026年7月12日 由心脏科专科门诊医生推荐。',
    journey_edu_completed: '已阅读科普内容',
    journey_edu_completed_desc: '已在新加坡 HealthHub 上完成津贴、科普视频和常见问答的阅读。',
    journey_slot_booked: '已预约咨询时段',
    journey_slot_booked_desc: '已成功预约 {date} @ {time} 国立大学医院 (NUH) 基因诊所。',
    journey_slot_action_needed: '需要采取行动：请选择您的政府资助基因咨询预约时段。',
    journey_attend_counselling: '到场出席基因咨询',
    journey_receive_results: '获取基因检测报告',
    journey_receive_results_desc: '在抽取血样 4 周后，医生将和您共同讨论预防步骤和个性化药物治疗方案。',
    lock_healthhub_preview: 'HealthHub 锁屏推送预览',
    lock_just_now: '刚刚',
    lock_counselling_reminder: '基因咨询就诊提醒',
    lock_counselling_confirmed_msg: '您的基因咨询预约已确认，时间为 {date} {time}。请点击以完善您的准备清单。',
    lock_counselling_tap_confirm_msg: '请确认您将于 {date} @ {time} 参加 FH 基因咨询。',
    lock_trigger_push_alert: '触发模拟锁屏推送提醒',
    lock_confirm_attendance_btn: '确认到场出席',
    lock_reschedule_btn: '重新安排预约',
    lock_read_prep_btn: '查看就诊准备说明',
    lock_tap_confirm_db_msg: '点击“确认到场出席”将实时在新加坡卫生部 HealthHub 数据库中为您登记到场确认状态。',
    lock_swipe_hint: '向上滑动以查看已登记的电子凭证',
    profile_female_age: '女 • 36岁',
    profile_full_name_val: 'Lisa Ho Siew Lan (何秀兰)',
    profile_dob_val: '1989年8月14日 (36岁)',
    profile_nationality_val: '新加坡公民',
    profile_residential_val: '宏茂桥10道第451座, #08-122, 新加坡 560451',
    profile_blood_group_val: 'O Rh+ (阳性)',
    profile_height_weight_val: '162 厘米 / 54 公斤 (BMI 20.6)',
    profile_cholesterol_level_val: 'LDL 5.4 mmol/L (风险偏高)',
    profile_active_referral_val: 'FH 基因检测',
    profile_referred_by_val: '由心脏专科门诊医生推荐',
    profile_card_expiry_val: '2028年12月31日',
    profile_father_history: '父亲 (48岁时确诊):',
    profile_father_history_desc: '冠心病 (血管成形术与支架)',
    profile_grandfather_history: '祖父 (52岁时去世):',
    profile_grandfather_history_desc: '致命性心肌梗死 (急性心脏病发作)',
    profile_aunt_history: '姑姑:',
    profile_aunt_history_desc: '极高胆固醇 (使用他汀类药物治疗)',
    profile_mother_history: '母亲与兄弟姐妹:',
    profile_mother_history_desc: '无早期心脏病史申报',
    profile_care_coordination: '医疗照护协调',
    profile_primary_clinic_val: '宏茂桥综合诊疗所',
    profile_referred_clinic_val: '国大医院 (NUH) 基因诊所',
    profile_emergency_contact_val: 'Ho Chin Teck (何振德)',
    profile_relationship_no_val: '配偶 • 9876 5432',
    profile_privacy_statement: '您的基因档案数据受到新加坡国家隐私法和人寿保险公会 (LIA) 暂停条例的完全保护。未经您的明确同意，您的详细信息绝不会被共享。',
    settings_option_sms_only: '仅限短信通知 (+65 9123 4567)',
    settings_option_push_only: '仅限 HealthHub 应用推送',
    settings_option_both: '短信与应用推送（推荐）',
    settings_help_sms: '提醒将通过短信直接发送到您注册的手机号码。',
    settings_help_push: '提醒将通过 HealthHub 应用程序显示在您的手机锁屏上。',
    settings_help_both: '系统将同时发送短信和应用推送提醒，以防年长者遗漏重要转诊通知。',
    settings_freq_monthly: '按月发送（科普资讯）',
    settings_freq_2_weeks: '就诊前 2 周（首次提醒）',
    settings_freq_1_week: '就诊前 1 周（推荐，强效提醒）',
    settings_freq_1_day: '就诊前 1 天（最后就诊准备确认）',
    settings_sms_preview_title: '短信提醒预览',
    settings_sms_verified_sender: '卫生部官方发送渠道',
    settings_lockscreen_preview_title: 'HealthHub 应用锁屏推送预览',
    settings_lockscreen_header: '新加坡 HealthHub • 刚刚',
    settings_sms_prefix: 'MOH HealthHub: 您的 FH 基因咨询预约已确认，时间为 {date} {time}，地点为国立大学医院基因诊所。最高 75% 的政府津贴已通过审核。请携带您的 NRIC/Singpass。详情：https://hh.gov.sg/fh-ref',
    journey_prep_title: '就诊前准备清单',
    journey_prep_desc: '确保您清楚了解就诊细节以及需要携带的家族病史报告。请仔细核对我们的指南。',
    journey_review_checklist_btn: '立即核对准备清单',
    lockscreen_telco: '新加坡电信 (Singtel)',
    lockscreen_date: '2026年7月15日 星期三',
    lockscreen_days_left: '剩余 7 天',
    lockscreen_push_msg: '您的基因咨询预约已确认，时间为 {date} {time}。请点击以完善您的准备清单。',
    lockscreen_tap_confirm_info: '点击“确认到场出席”将实时在新加坡卫生部 HealthHub 数据库中为您登记到场确认状态。',
    lockscreen_swipe_hint: '向上滑动以查看已登记的电子凭证',
    booking_subsidies_computed: '政府卫生部津贴已根据您绑定的 Singpass 身份自动计算。',
    booking_no_slots_alert: '此日期没有可选的预约时段。请选择上方日历中高亮显示的日期。',
    booking_assigned_specialist: '为您分配的专科临床专家',
    booking_address_label: '地址：',
    booking_date_label: '日期：',
    booking_time_label: '时间：',
    booking_duration_label: '门诊时长：',
    booking_out_of_pocket_label: '预计个人自付总金额：',
    // Bottom Navigation Bar
    nav_home: '主页',
    nav_learn: '科普',
    nav_book: '预约',
    nav_journey: '历程',
    nav_profile: '档案',
    // Home Page Profiles
    home_profile_lisa: '何秀兰 (LISA HO)',
    home_profile_spouse: '何振德 (HO CHIN TECK)',
    // Home Page Programmes
    prog_active_hub: '活跃计划',
    prog_diabetes_title: '糖尿病健康计划',
    prog_diabetes_desc: '用于管理和预防糖尿病的个性化指南。',
    prog_resource: '健康资源',
    prog_mental_title: '心理健康提升计划',
    prog_mental_desc: '正念医学指导和提供情感支持的安全网络。',
    // Book Screen Selector Buttons
    booking_close_selector_btn: '关闭选择器',
    booking_change_estate_btn: '更改小区 / GPS定位',
    // Clinic Names & Addresses
    clinic_nuh_name: '新加坡国立大学医院 (NUH) 基因诊所',
    clinic_nuh_address: '肯特岗下路5号，主楼B区，新加坡 119074',
    clinic_sgh_name: '新加坡中央医院 (SGH) 基因医学部',
    clinic_sgh_address: '欧南路，学术医学大楼地下一层，新加坡 169608',
    clinic_ttsh_name: '陈笃生医院 (TTSH) 临床基因组学部',
    clinic_ttsh_address: '惹兰陈笃生11号，4B诊所，新加坡 308433',
    clinic_kkh_name: '竹脚妇幼医院 (KKH) 基因诊所',
    clinic_kkh_address: '武吉知马路100号，儿童大楼5层，新加坡 229899',
    // Doctors
    doc_helen_lim: '林海伦医生 (Dr. Helen Lim)',
    doc_albert_chiang: '蒋艾伯特医生 (Dr. Albert Chiang)',
    doc_marcus_goh: '吴马库斯医生 (Dr. Marcus Goh)',
    doc_fiona_lee: '李菲奥娜医生 (Dr. Fiona Lee)',
    doc_benjamin_chew: '周本杰明医生 (Dr. Benjamin Chew)',
    doc_sarah_tan: '陈莎拉医生 (Dr. Sarah Tan)',
    doc_claire_wong: '黄克莱尔医生 (Dr. Claire Wong)',
    doc_jeanette_tan: '陈珍妮特医生 (Dr. Jeanette Tan)',
    // Specialist Roles
    role_senior_genetic_counsellor: '高级基因咨询师',
    role_consultant_cardiogeneticist: '心血管基因专科顾问医生',
    role_principal_genetics_specialist: '首席基因学家',
    role_senior_clinical_geneticist: '高级临床基因学家',
    role_consultant_paediatric_geneticist: '儿科基因专科顾问医生',
    role_lead_paediatric_counsellor: '首席儿科基因咨询师',
    role_consultant_geneticist: '基因专科顾问医生',
  },
  ta: {
    health: 'Health',
    hub: 'Hub',
    active_user: 'செயலில் உள்ள பயனர்',
    chas_blue: 'CHAS ப்ளூ உறுப்பினர்',
    action_recommended: 'நடவடிக்கை பரிந்துரைக்கப்படுகிறது',
    
    fh_referral_title: 'FH மரபணு சோதனை பரிந்துரை',
    fh_referral_desc: 'உங்கள் சமீபத்திய கொலஸ்ட்ரால் முடிவுகளின் அடிப்படையில், உங்கள் ஆரோக்கியத்தை நன்கு புரிந்துகொள்ள FH மரபணு சோதனையை மருத்துவர் பரிந்துரைக்கிறார்.',
    recommended_next_step: 'பரிந்துரைக்கப்பட்ட அடுத்த படி',
    book_counselling_step: 'உங்களின் சோதனைக்கு முந்தைய ஆலோசனையை முன்பதிவு செய்யவும்.',
    next_appointment: 'அடுத்த சந்திப்பு',
    learn_why: 'காரணத்தை அறிய',
    why_referred_btn: 'ஏன் பரிந்துரைக்கப்பட்டேன்?',
    book_now_btn: 'முன்பதிவு செய்ய',
    manage_slot_btn: 'முன்பதிவை நிர்வகிக்க',
    your_journey: 'உங்கள் சிகிச்சை பயணம்',
    step_referral: 'பரிந்துரை',
    step_counselling: 'ஆலோசனை முன்பதிவு',
    step_testing: 'மரபணு சோதனை',
    
    quick_links: 'விரைவு இணைப்புகள்',
    edit: 'திருத்து',
    link_appointments: 'சந்திப்புகள் முன்பதிவு',
    link_learn: 'விவரம் & கல்வி',
    link_subsidies: 'அரசு மானியங்கள்',
    link_care_team: 'சிகிச்சைக் குழு',
    link_call: 'நேரடி அழைப்பு',
    link_faqs: 'கேள்வி பதில்கள்',
    
    your_care_team: 'உங்கள் சிகிச்சைக் குழு',
    specialist_role: 'மூத்த மரபணு ஆலோசகர்',
    specialist_hospital: 'National University Hospital',
    
    referral_details_title: 'பரிந்துரை விவரங்கள்',
    why_am_i_referred_title: 'நான் ஏன் FH மரபணு சோதனைக்கு பரிந்துரைக்கப்பட்டேன்?',
    explanation_1: 'உங்கள் கொழுப்பு அளவு மிகவும் அதிகமான LDL (கெட்ட) கொழுப்பைக் காட்டுகிறது. FH என்பது மரபுவழி நிலை, அதாவது வாழ்க்கை முறை மட்டுமே இதற்குக் காரணம் அல்ல.',
    explanation_2: 'ஒரு குறிப்பிட்ட மரபணு மாறுபாடு காரணமா என்பதை மரபணு சோதனை உறுதிப்படுத்துகிறது. இது உங்களுக்கும் உங்கள் குடும்பத்திற்கும் மிகவும் பயனுள்ள தடுப்பு சிகிச்சைகளை வடிவமைக்க உதவுகிறது.',
    govt_subsidies_title: 'அரசு மானியங்கள்',
    subsidies_desc: 'CHAS ப்ளூ / முன்னோடி தலைமுறையினருக்கு 75% வரை MOH மானியம். மீதமுள்ள கட்டணத்தை செலுத்த MediSave ஐயும் பயன்படுத்தலாம்.',
    what_should_i_do: 'நான் இப்போது என்ன செய்ய வேண்டும்?',
    what_should_i_do_desc: 'உங்களது 45 நிமிட ஆலோசனை சந்திப்பை முன்பதிவு செய்யுமாறு பரிந்துரைக்கிறோம். இந்த அமர்வுக்கு எவ்வித கட்டாயமும் இல்லை, மேலும் இது மருத்துவ தாக்கங்களை தெளிவாக விளக்கும்.',
    book_counselling_session: 'ஆலோசனை அமர்வை முன்பதிவு செய்',
    
    education_hub_title: 'மரபணு கல்வி மையம்',
    tab_guides: 'வீடியோ & வழிகாட்டிகள்',
    tab_checklist: 'சரிபார்ப்புப் பட்டியல்',
    tab_faqs: 'கேள்விகள் & பதில்கள்',
    
    select_clinic_title: 'மருத்துவமனையைத் தேர்வு செய்யவும்',
    search_placeholder: 'மருத்துவமனை அல்லது இடத்தை தேடு...',
    use_gps: 'எனது நேரடி ஜி.பி.எஸ் பயன்படுத்தவும்',
    gps_calculating: 'இருப்பிடத்தைக் கண்டறிகிறது...',
    available_slots: 'கிடைக்கும் நேரங்கள்',
    review_booking_title: 'முன்பதிவை சரிபார்க்கவும்',
    confirm_booking_btn: 'முன்பதிவை உறுதி செய்',
    appointment_confirmed_title: 'சந்திப்பு உறுதி செய்யப்பட்டது!',
    booking_success_desc: 'உங்கள் ஆலோசனை முன்பதிவு உறுதி செய்யப்பட்டது. உங்களுக்கு எஸ்.எம்.எஸ் மற்றும் புஷ் அறிவிப்பு நினைவூட்டல்கள் அனுப்பப்படும்.',
    add_to_calendar: 'நாட்காட்டியில் சேர்க்கவும்',
    reschedule_slot: 'முன்பதிவு மாற்றம்',
    back_to_home: 'முகப்புப் பக்கத்திற்குச் செல்',
    
    settings_title: 'அமைப்புகள்',
    settings_desc: 'மரபணு சோதனை பரிந்துரைகள் மற்றும் சந்திப்பு விழிப்பூட்டல்களை எப்போது பெறுவது என்பதை அமைக்கவும்.',
    active_reminders: 'செயலில் உள்ள FH நினைவூட்டல்கள்',
    active_reminders_desc: 'கல்வி புதுப்பிப்புகள் மற்றும் நினைவூட்டல்களைப் பெறுங்கள்.',
    notification_channel: 'அறிவிப்பு சேனல்',
    reminder_frequency: 'நினைவூட்டல் அதிர்வெண்',
    frequency_desc: 'சந்திப்பு தேதிக்கு எவ்வளவு காலத்திற்கு முன்பு நினைவூட்டல் அனுப்பப்பட வேண்டும் என்பதை அமைக்கவும்.',
    freq_comprehensive: 'விரிவானது (Comprehensive)',
    freq_standard: 'தரநிலையானது (Standard)',
    freq_minimal: 'குறைந்தது (Minimal)',
    freq_comprehensive_desc: 'விரிவானது: உங்கள் சந்திப்பிற்கு 1 மாதம், 2 வாரங்கள், 1 வாரம் மற்றும் 1 நாளுக்கு முன்பு நினைவூட்டல்களை அனுப்புகிறது.',
    freq_standard_desc: 'தரநிலையானது: உங்கள் சந்திப்பிற்கு 1 வாரம் மற்றும் 1 நாளுக்கு முன்பு நினைவூட்டல்களை அனுப்புகிறது.',
    freq_minimal_desc: 'குறைந்தது: உங்கள் சந்திப்பிற்கு 1 நாளுக்கு முன்பு ஒரு நினைவூட்டலை அனுப்புகிறது.',
    active_schedule: 'செயலில் உள்ள அட்டவணை',
    active_freq_comprehensive: 'சந்திப்பிற்கு 1 மாதம், 2 வாரங்கள், 1 வாரம், & 1 நாளுக்கு முன் நினைவூட்டல்',
    active_freq_standard: 'சந்திப்பிற்கு 1 வாரம் & 1 நாளுக்கு முன் நினைவூட்டல்',
    active_freq_minimal: 'சந்திப்பிற்கு 1 நாளுக்கு முன் நினைவூட்டல் மட்டும்',
    lang_pref_title: 'மொழி விருப்பத்தேர்வுகள்',
    lang_pref_desc: 'உங்களுக்கு விருப்பமான மொழியைத் தேர்ந்தெடுக்கவும். இது சிங்கப்பூரின் அனைத்து சமூகத்தினருக்கும் உதவும் வகையில் அனைத்து உரை உள்ளடக்கத்தையும் மாறும் வகையில் புதுப்பிக்கிறது.',
    select_app_language: 'செயலி மொழியைத் தேர்ந்தெடுக்கவும்',
    
    progress_journey_title: 'எனது சிகிச்சை பயணம்',
    status_unbooked: 'ஆலோசனை முன்பதிவு தேவை',
    status_booked: 'சந்திப்பு திட்டமிடப்பட்டுள்ளது',
    status_confirmed: 'வருகை உறுதி செய்யப்பட்டது',
    unbooked_journey_desc: 'செயலில் உள்ள உங்கள் கார்டியாக் மரபணு பரிந்துரைக்கு நீங்கள் ஒரு ஆலோசனை அமர்வை திட்டமிட வேண்டும்.',
    timeline_title: 'ஊடாடும் பரிந்துரை காலவரிசை',
    
    back: 'பின்செல்',

    // New additions for full translation support
    lab_reports_btn: 'ஆய்வக அறிக்கைகள்',
    med_reports_btn: 'மருத்துவ அறிக்கைகள்',
    med_refill_btn: 'மருந்து நிரப்புதல்',
    payment_btn: 'கட்டணம்',
    health_profiles: 'சுகாதார விவரக்குறிப்புகள்',
    view_all_btn: 'அனைத்தையும் பார்',
    programmes_title: 'திட்டங்கள்',
    referred_intro_title: 'நான் ஏன் பரிந்துரைக்கப்பட்டேன்?',
    referred_hi_lisa: 'வணக்கம் லிசா.',
    referred_doctor_rec: 'உங்களின் சமீபத்திய கொலஸ்ட்ரால் முடிவுகளை ஆய்வு செய்த பின்னர், உங்கள் மருத்துவர் உங்களுக்கு மரபணு சோதனையை பரிந்துரைத்துள்ளார்.',
    referred_means: 'இதன் பொருள் என்ன என்பது இங்கே.',
    referred_why_doctor: 'உங்கள் மருத்துவர் உங்களை பரிந்துரைத்ததற்கான காரணம்',
    referred_cholesterol_may_fh: 'உங்களுக்கு FH (உயர் கொழுப்பு நிலை) இருக்க வாய்ப்புள்ளது என்பதை உங்கள் கொலஸ்ட்ரால் முடிவுகள் காட்டுகின்றன.',
    not_mean_have_fh: 'உங்களுக்கு நிச்சயம் FH இருக்கிறது என்று அர்த்தமல்ல.',
    genetic_testing_confirms: 'மரபணு சோதனை மட்டுமே இதற்கான காரணத்தை உறுதிப்படுத்த உதவும்.',
    referred_results_help_team: 'சரியான சிகிச்சையைத் தேர்வுசெய்ய இந்த முடிவுகள் உங்கள் மருத்துவக் குழுவிற்கு உதவும்.',
    why_this_matters: 'இது ஏன் முக்கியம்',
    early_diagnosis: 'ஆரம்ப கால கண்டறிதல்',
    early_diagnosis_desc: 'சிகிச்சையை விரைவாகத் தொடங்குங்கள்.',
    protect_family: 'உங்கள் குடும்பத்தைப் பாதுகாக்கவும்',
    protect_family_desc: 'இது குடும்பங்களில் பரவக்கூடிய ஒரு மரபுவழி நிலை.',
    personalized_care: 'தனிப்பயனாக்கப்பட்ட சிகிச்சை',
    personalized_care_desc: 'முடிவுகள் உங்கள் சிகிச்சை முறையை வழிநடத்த உதவும்.',
    what_happens_next: 'அடுத்து என்ன நடக்கும்?',
    step_referral_received: 'பரிந்துரை பெறப்பட்டது',
    step_learn_about_fh: 'FH பற்றி அறியவும்',
    step_current: 'தற்போதைய',
    step_pre_test_counselling: 'முன் சோதனை ஆலோசனை',
    step_genetic_results: 'மரபணு சோதனை முடிவுகள்',
    referred_next_step_learning: 'உங்களது முன்-சோதனை ஆலோசனை சந்திப்பில் பங்கேற்பதற்கு முன்பு FH பற்றி மேலும் அறிந்து கொள்வதே அடுத்த படியாகும்.',
    referred_before_app: 'உங்கள் சந்திப்பிற்கு முன்',
    referred_spend_time: 'ஆலோசனை சந்திப்பிற்கு முன் 2-3 நிமிடங்கள் செலவழித்து FH பற்றி அறிந்து கொள்ளவும்.',
    referred_short_what_is: 'FH என்றால் என்ன?',
    referred_short_why: 'ஏன் சோதனை?',
    referred_short_process: 'சோதனை செயல்முறை',
    referred_short_costs: 'கட்டணங்கள்',
    referred_short_insurance: 'காப்பீடு',
    referred_continue_learn: 'சந்திப்பிற்கு முன் FH பற்றி தொடர்ந்து அறிந்து கொள்ளவும்.',
    booking_secure_title: 'பாதுகாப்பான சந்திப்பு முன்பதிவு',
    booking_confirmed_status: 'உங்கள் சந்திப்பு உறுதி செய்யப்பட்டுள்ளது',
    booking_subsidized_slot: 'MOH மானியம் பெற்ற நேரம்',
    booking_care_clinic: 'சிகிச்சை கிளினிக்:',
    booking_specialist: 'நிபுணர்:',
    booking_scheduled_date: 'திட்டமிடப்பட்ட தேதி:',
    booking_confirmed_time: 'உறுதி செய்யப்பட்ட நேரம்:',
    booking_session_duration: 'அமர்வு காலம்:',
    booking_out_of_pocket: 'நேரடி கட்டணம்:',
    booking_chas_subsidized: 'CHAS மானியம்',
    booking_add_device_calendar: 'நாட்காட்டியில் சேர்க்கவும்',
    booking_essential_prep: 'முக்கிய தயாரிப்பு வழிமுறைகள்',
    booking_prep_no_fasting: 'உண்ணாவிரதம் தேவையில்லை: உங்கள் அமர்வுக்கு முன் சாதாரணமாக சாப்பிட்டு குடிக்கவும்.',
    booking_prep_id_verif: 'அடையாள சரிபார்ப்பு: உங்கள் அசல் NRIC அட்டை அல்லது Singpass மூலம் உள்நுழையவும்.',
    booking_prep_checklist: 'உங்கள் சந்திப்பிற்கு முன் முன்-ஆலோசனை சரிபார்ப்புப் பட்டியலை முடிக்கவும்',
    booking_view_checklist: 'முன்-சந்திப்பு சரிபார்ப்புப் பட்டியலைப் பார்',
    booking_reschedule_slot: 'முன்பதிவு மாற்றம்',
    booking_cancel_slot: 'சந்திப்பு முன்பதிவை ரத்து செய்',
    booking_eligible_subsidies: 'உங்கள் மருத்துவ பரிந்துரையின் அடிப்படையில், இந்த பதிவு செய்யப்பட்ட நிறுவனங்களில் 75% வரை MOH மானியங்களைப் பெற நீங்கள் தகுதியுடையவர்.',
    booking_nearest_tag: 'அருகிலுள்ள',
    booking_select_counselling_slot: 'ஆலோசனை நேரத்தைத் தேர்ந்தெடுக்கவும்',
    booking_choose_subsidized_slot: 'உங்களுக்கு மானியம் பெற்ற மரபணு ஆலோசனை நேரத்தைத் தேர்ந்தெடுக்கவும்.',
    booking_select_month: 'மாதத்தைத் தேர்ந்தெடு',
    booking_reschedule_alert: 'முன்பதிவு மாற்ற முறை செயலில் உள்ளது: கீழே புதிய நேரத்தைத் தேர்ந்தெடுக்கவும்.',
    booking_nric_verified: 'தயார் & பதிவு செய்யப்பட்டது • மருத்துவ சேர்க்கைக்கு முன் NRIC/Singpass சரிபார்க்கப்பட்டது.',
    booking_unverified_alert: 'வருகை சரிபார்க்கப்படவில்லை. வருகையை உறுதிப்படுத்த பூட்டுத் திரை அறிவிப்பு அல்லது அமைப்புகளைத் தட்டவும்.',
    booking_session_desc: 'குடும்ப கவலைகளுக்கு பதிலளிக்கவும் சோதனையை இறுதி செய்யவும் 45 நிமிட அமர்வு.',
    booking_review_details: 'முன்பதிவை சரிபார்க்கவும்',
    booking_confirm_slot_btn: 'முன்பதிவை உறுதி செய்',
    booking_add_calendar_success: 'ஆப்பிள் காலண்டர் .ics நிகழ்வு வெற்றிகரமாக பதிவிறக்கம் செய்யப்பட்டது!',
    profile_my_health_profile: 'எனது சுகாதார விவரக்குறிப்பு',
    profile_singpass_linked: 'Singpass இணைக்கப்பட்டுள்ளது',
    profile_moh_identity_cleared: 'MOH அடையாள சரிபார்ப்பு முடிந்தது',
    profile_personal_particulars: 'தனிப்பட்ட விவரங்கள்',
    profile_full_name: 'முழு பெயர்:',
    profile_nric_fin: 'NRIC/FIN:',
    profile_dob: 'பிறந்த தேதி:',
    profile_nationality: 'தேசியம்:',
    profile_mobile_number: 'கைபேசி எண்:',
    profile_email_address: 'மின்னஞ்சல் முகவரி:',
    profile_residential: 'இருப்பிடம்:',
    profile_clinical_metrics: 'மருத்துவ அளவீடுகள் & அபாயங்கள்',
    profile_blood_group: 'இரத்த வகை:',
    profile_height_weight: 'உயரம் / எடை:',
    profile_known_allergies: 'அறியப்பட்ட ஒவ்வாமைகள்:',
    profile_none_declared: 'ஒன்றுமில்லை',
    profile_cholesterol_level: 'கொலஸ்ட்rஆல் அளவு:',
    profile_elevated_risk: 'அதிக அபாயம்',
    profile_active_referral: 'செயலில் உள்ள பரிந்துரை:',
    profile_referred_by: 'இதயவியல் நிபுணரால் பரிந்துரைக்கப்பட்டது',
    profile_subsidies_financing: 'மானியங்கள் & நிதி',
    profile_chas_blue_member: 'CHAS ப்ளூ அடுக்கு உறுப்பினர்',
    profile_chas_subsidy_level: 'MOH மானியம் 75% வரை வரையறுக்கப்பட்டுள்ளது',
    profile_chas_card_expiry: 'CHAS அட்டை காலாவதி தேதி:',
    profile_medisave_account: 'MediSave கணக்கு:',
    profile_medisave_note: '*வெளிநோயாளி மரபணு ஆலோசனை மற்றும் சோதனை கட்டணங்களை MOH MediSave விதிகளின் கீழ் முழுமையாகப் பெறலாம்.',
    profile_family_cardiac_history: 'குடும்ப இதய வரலாறு',
    profile_family_history_desc: 'உயர் கொழுப்பு நிலை (FH) பெற்றோரிடமிருந்து பரவுகிறது. உங்கள் குடும்ப வரலாற்றை அறிவது சோதனைக்கு முக்கியமான பின்னணியை வழங்குகிறது:',
    journey_my_patient_journey: 'எனது சிகிச்சை பயணம்',
    journey_appointment_progress: 'உங்கள் சந்திப்பு முன்னேற்றம்',
    journey_appointment_status: 'சந்திப்பு நிலை',
    journey_interactive_referral_timeline: 'ஊடாடும் பரிந்துரை காலவரிசை',
    journey_referral_received: 'பரிந்துரை பெறப்பட்டது',
    journey_referral_received_desc: '12 ஜூலை 2026 அன்று இதயவியல் நிபுணரால் பரிந்துரைக்கப்பட்டது.',
    journey_edu_completed: 'கல்விப் பொருட்கள் மதிப்பாய்வு செய்யப்பட்டன',
    journey_edu_completed_desc: 'சிங்கப்பூர் ஹெல்த்ஹப்பில் மானியங்கள், மருத்துவ வீடியோ மற்றும் கேள்வி பதில்கள் சரிபார்க்கப்பட்டன.',
    journey_slot_booked: 'ஆலோசனை நேரம் முன்பதிவு செய்யப்பட்டது',
    journey_slot_booked_desc: '{date} அன்று {time} மணிக்கு NUH மரபணு கிளினிக்கில் திட்டமிடப்பட்டுள்ளது.',
    journey_slot_action_needed: 'நடவடிக்கை தேவை: உங்களுக்கு மானியம் பெற்ற மரபணு ஆலோசனை நேரத்தைத் தேர்ந்தெடுக்கவும்.',
    journey_attend_counselling: 'மரபணு ஆலோசனையில் பங்கேற்கவும்',
    journey_receive_results: 'மரபணு முடிவுகளைப் பெறவும்',
    journey_receive_results_desc: 'இரத்தம் எடுக்கப்பட்ட 4 வாரங்களுக்குப் பிறகு தடுப்பு நடவடிக்கைகள் மற்றும் சிகிச்சை பற்றிய கலந்துரையாடல்.',
    lock_healthhub_preview: 'பூட்டுத் திரை அறிவிப்பு முன்னோட்டம்',
    lock_just_now: 'இப்போது',
    lock_counselling_reminder: 'ஆலோசனை சந்திப்பு நினைவூட்டல்',
    lock_counselling_confirmed_msg: 'உங்கள் மரபணு ஆலோசனை {date} அன்று {time} மணிக்கு உறுதிப்படுத்தப்பட்டுள்ளது. சரிபார்ப்புப் பட்டியலை முடிக்க தட்டவும்.',
    lock_counselling_tap_confirm_msg: '{date} @ {time} மணிக்கு உங்கள் FH மரபணு ஆலோசனையை உறுதிப்படுத்தவும்.',
    lock_trigger_push_alert: 'பூட்டுத் திரை அறிவிப்பை உருவகப்படுத்து',
    lock_confirm_attendance_btn: 'வருகையை உறுதி செய்',
    lock_reschedule_btn: 'முன்பதிவு மாற்றம்',
    lock_read_prep_btn: 'தயாரிப்பு வழிகாட்டியைப் படி',
    lock_tap_confirm_db_msg: 'சிங்கப்பூர் ஹெல்த்ஹப் தரவுத்தளத்தில் உங்கள் வருகையை உடனடியாக பதிவு செய்ய "வருகையை உறுதி செய்" என்பதைத் தட்டவும்.',
    lock_swipe_hint: 'பதிவு செய்யப்பட்ட சான்றுகளைத் திறக்க மேலே ஸ்வைப் செய்யவும்',
    profile_female_age: 'பெண் • 36',
    profile_full_name_val: 'Lisa Ho Siew Lan',
    profile_dob_val: '14 ஆகஸ்ட் 1989 (36 வயது)',
    profile_nationality_val: 'சிங்கப்பூர் குடிமகன்',
    profile_residential_val: 'பிளாக் 451 ஆங் மோ கியோ அவென்யூ 10, #08-122, சிங்கப்பூர் 560451',
    profile_blood_group_val: 'O Rh+ (பாசிட்டிவ்)',
    profile_height_weight_val: '162 செ.மீ / 54 கிலோ (BMI 20.6)',
    profile_cholesterol_level_val: 'LDL 5.4 mmol/L (அதிகரித்த ஆபத்து)',
    profile_active_referral_val: 'FH மரபணு சோதனை',
    profile_referred_by_val: 'இருதய நோய் நிபுணரால் பரிந்துரைக்கப்பட்டது',
    profile_card_expiry_val: '31 டிசம்பர் 2028',
    profile_father_history: 'தந்தை (கண்டறியப்பட்ட வயது 48):',
    profile_father_history_desc: 'கொரோனரி இதய நோய் (ஆஞ்சியோபிளாஸ்டி & ஸ்டென்ட்)',
    profile_grandfather_history: 'தந்தைவழி பாட்டனார் (இறந்த வயது 52):',
    profile_grandfather_history_desc: 'மரணத்தை விளைவிக்கும் மாரடைப்பு (கடுமையான மாரடைப்பு)',
    profile_aunt_history: 'தந்தைவழி அத்தை:',
    profile_aunt_history_desc: 'கடுமையான கொலஸ்ட்ரால் (ஸ்டேடின்களுடன் சிகிச்சை)',
    profile_mother_history: 'தாய் மற்றும் உடன்பிறப்புகள்:',
    profile_mother_history_desc: 'ஆரம்பகால இதய நோய் வரலாறு இல்லை',
    profile_care_coordination: 'சிகிச்சை ஒருங்கிணைப்பு',
    profile_primary_clinic_val: 'ஆங் மோ கியோ பாலிக்ளினிக்',
    profile_referred_clinic_val: 'NUH மரபணு கிளினிக்',
    profile_emergency_contact_val: 'Ho Chin Teck',
    profile_relationship_no_val: 'துணைவி • 9876 5432',
    profile_privacy_statement: 'சிங்கப்பூரின் தேசிய தனியுரிமைச் சங்கங்கள் மற்றும் ஆயுள் காப்பீட்டுச் சங்கத்தின் (LIA) தற்காலிகத் தடை ஆகியவற்றின் கீழ் உங்கள் மரபணு விவரத் தரவு முழுமையாகப் பாதுகாக்கப்படுகிறது. உங்கள் வெளிப்படையான ஒப்புதல் இன்றி உங்கள் விவரங்கள் ஒருபோதும் பகிர込ま மாட்டாது.',
    settings_option_sms_only: 'எஸ்.எம்.எஸ் செய்திகள் மட்டும் (+65 9123 4567)',
    settings_option_push_only: 'ஹெல்த்ஹப் செயலி புஷ் அறிவிப்புகள்',
    settings_option_both: 'எஸ்.எம்.எஸ் மற்றும் புஷ் அறிவிப்புகள் இரண்டும் (பரிந்துரைக்கப்படுகிறது)',
    settings_help_sms: 'பதிவுசெய்யப்பட்ட உங்களது கைபேசி எண்ணிற்கு எஸ்.எம்.எஸ் மூலம் நினைவூட்டல் நேரடியாக அனுப்பப்படும்.',
    settings_help_push: 'ஹெல்த்ஹப் செயலியிலிருந்து நினைவூட்டல் உங்களது பூட்டுத் திரையில் தோன்றும்.',
    settings_help_both: 'எஸ்.எம்.எஸ் மற்றும் புஷ் அறிவிப்புகள் இரண்டிலும் நினைவூட்டல்கள் அனுப்பப்படும்.',
    settings_freq_monthly: 'மாதாந்திர தகவல் (கல்விப் பொருட்கள்)',
    settings_freq_2_weeks: '2 வாரங்களுக்கு முன்பு (தொடக்க நினைவூட்டல்)',
    settings_freq_1_week: '1 வாரத்திற்கு முன்பு (அதிக பாதுகாப்பு கொண்டது)',
    settings_freq_1_day: '1 நாளுக்கு முன்பு (இறுதி தயாரிப்பு சரிபார்ப்பு)',
    settings_sms_preview_title: 'எஸ்.எம்.எஸ் நினைவூட்டல் முன்னோட்டம்',
    settings_sms_verified_sender: 'அங்கீகரிக்கப்பட்ட MOH அனுப்புநர்',
    settings_lockscreen_preview_title: 'பூட்டுத் திரை அறிவிப்பு முன்னோட்டம்',
    settings_lockscreen_header: 'ஹெல்த்ஹப் சிங்கப்பூர் • இப்போது',
    settings_sms_prefix: 'MOH HealthHub: {date} அன்று {time} மணிக்கு NUH மரபணு கிளினிக்கில் உங்கள் FH ஆலோசனை உறுதிப்படுத்தப்பட்டுள்ளது. 75% வரை மானியம் வழங்கப்பட்டுள்ளது. Singpass கொண்டு வரவும். விவரம்: https://hh.gov.sg/fh-ref',
    journey_prep_title: 'தயாரிப்பு சரிபார்ப்புப் பட்டியல்',
    journey_prep_desc: 'நீங்கள் எதை எதிர்பார்க்க வேண்டும் மற்றும் என்ன குடும்ப வரலாற்று அறிக்கைகளைக் கொண்டு வர வேண்டும் என்பதை உறுதிப்படுத்திக் கொள்ளுங்கள். எங்கள் வழிகாட்டிகளைப் படிக்கவும்.',
    journey_review_checklist_btn: 'சரிபார்ப்பு பட்டியலை இப்போது சரிபார்க்கவும்',
    lockscreen_telco: 'சிங்கப்பூர் தொலைத்தொடர்பு',
    lockscreen_date: 'புதன்கிழமை, ஜூலை 15, 2026',
    lockscreen_days_left: '7 நாட்கள் உள்ளன',
    lockscreen_push_msg: 'உங்கள் மரபணு ஆலோசனை {date} அன்று {time} மணிக்கு உறுதிப்படுத்தப்பட்டுள்ளது. சரிபார்ப்புப் பட்டியலை முடிக்க தட்டவும்.',
    lockscreen_tap_confirm_info: 'சிங்கப்பூர் ஹெல்த்ஹப் தரவுத்தளத்தில் உங்கள் வருகையை உடனடியாக பதிவு செய்ய "வருகையை உறுதி செய்" என்பதைத் தட்டவும்.',
    lockscreen_swipe_hint: 'பதிவு செய்யப்பட்ட சான்றுகளைத் திறக்க மேலே ஸ்வைப் செய்யவும்',
    booking_subsidies_computed: 'உங்களது இணைக்கப்பட்ட Singpass நிலை மூலம் MOH மானியங்கள் தானாகவே கணக்கிடப்படும்.',
    booking_no_slots_alert: 'இந்த தேதியில் முன்பதிவு செய்ய இடங்கள் இல்லை. மேலே உள்ள காலண்டரில் சிறப்பிக்கப்பட்டுள்ள நாளைத் தேர்ந்தெடுக்கவும்.',
    booking_assigned_specialist: 'ஒதுக்கப்பட்ட மருத்துவ நிபுணர்',
    booking_address_label: 'முகவரி:',
    booking_date_label: 'தேதி:',
    booking_time_label: 'நேரம்:',
    booking_duration_label: 'அமர்வின் கால அளவு:',
    booking_out_of_pocket_label: 'மதிப்பிடப்பட்ட மொத்தக் கட்டணம்:',
    // Bottom Navigation Bar
    nav_home: 'முகப்பு',
    nav_learn: 'கற்க',
    nav_book: 'முன்பதிவு',
    nav_journey: 'பயணம்',
    nav_profile: 'விவரக்குறிப்பு',
    // Home Page Profiles
    home_profile_lisa: 'லிசா ஹோ (LISA HO)',
    home_profile_spouse: 'ஹோ சின் டெக் (HO CHIN TECK)',
    // Home Page Programmes
    prog_active_hub: 'செயலில் உள்ள மையம்',
    prog_diabetes_title: 'நீரிழிவு மையம்',
    prog_diabetes_desc: 'நீரிழிவு நோயை நிர்வகிப்பதற்கும் தடுப்பதற்கும் தனிப்பயனாக்கப்பட்ட வழிகாட்டிகள்.',
    prog_resource: 'வளங்கள்',
    prog_mental_title: 'மன நலம்',
    prog_mental_desc: 'உணர்ச்சி பாதுகாப்புக்கான தியான வழிகாட்டிகள் மற்றும் ஆதரவு நெட்வொர்க்குகள்.',
    // Book Screen Selector Buttons
    booking_close_selector_btn: 'தேர்வியைக் மூடு',
    booking_change_estate_btn: 'எஸ்டேட் / ஜிபிஎஸ் மாற்றவும்',
    // Clinic Names & Addresses
    clinic_nuh_name: 'தேசிய பல்கலைக்கழக மருத்துவமனை மரபணு கிளினிக் (NUH)',
    clinic_nuh_address: '5 லோயர் கென்ட் ரிட்ஜ் ரோடு, முதன்மை கட்டிடம் மண்டலம் B, சிங்கப்பூர் 119074',
    clinic_sgh_name: 'சிங்கப்பூர் பொது மருத்துவமனை மரபியல் சேவை (SGH)',
    clinic_sgh_address: 'அவுட்ராம் ரோடு, கல்வி மருத்துவம் அடித்தளம் 1, சிங்கப்பூர் 169608',
    clinic_ttsh_name: 'டான் டோக் செங் மருத்துவமனை மருத்துவ மரபியல் (TTSH)',
    clinic_ttsh_address: '11 ஜாலான் டான் டோக் செங், கிளினிக் 4B, சிங்கப்பூர் 308433',
    clinic_kkh_name: 'கேகே பெண்கள் மற்றும் குழந்தைகள் மருத்துவமனை மரபணு கிளினிக் (KKH)',
    clinic_kkh_address: '100 புக்கிட் திமா ரோடு, குழந்தைகள் கோபுரம் நிலை 5, சிங்கப்பூர் 229899',
    // Doctors
    doc_helen_lim: 'டாக்டர் ஹெலன் லிம்',
    doc_albert_chiang: 'டாக்டர் ஆல்பர்ட் சியாங்',
    doc_marcus_goh: 'டாக்டர் மார்கஸ் கோ',
    doc_fiona_lee: 'டாக்டர் பியோனா லீ',
    doc_benjamin_chew: 'டாக்டர் பெஞ்சமின் செவ்',
    doc_sarah_tan: 'டாக்டர் சாரா டான்',
    doc_claire_wong: 'டாக்டர் கிளாரி வோங்',
    doc_jeanette_tan: 'டாக்டர் ஜீனெட் டான்',
    // Specialist Roles
    role_senior_genetic_counsellor: 'மூத்த மரபணு ஆலோசகர்',
    role_consultant_cardiogeneticist: 'இருதய மரபியல் ஆலோசகர்',
    role_principal_genetics_specialist: 'முதன்மை மரபியல் நிபுணர்',
    role_senior_clinical_geneticist: 'முதுநிலை மருத்துவ மரபியல் நிபுணர்',
    role_consultant_paediatric_geneticist: 'குழந்தை மருத்துவ மரபியல் ஆலோசகர்',
    role_lead_paediatric_counsellor: 'முதன்மை குழந்தை மருத்துவ ஆலோசகர்',
    role_consultant_geneticist: 'மரபியல் ஆலோசகர்',
  },
};

// Localized preCounsellingChecklist
export const getLocalizedChecklist = (lang: Language) => {
  switch (lang) {
    case 'ms':
      return [
        { id: 'prep-2', text: 'Ubat-ubatan semasa dan suplemen yang anda sedang ambil.', checked: false },
        { id: 'prep-3', text: 'Soalan yang ingin anda tanyakan kepada kaunselor genetik anda.', checked: false },
        { id: 'prep-4', text: 'NRIC atau Singpass untuk pendaftaran masuk.', checked: false },
      ];
    case 'zh':
      return [
        { id: 'prep-2', text: '您目前正在服用的药物和膳食补充剂。', checked: false },
        { id: 'prep-3', text: '您想向基因咨询师咨询的具体问题。', checked: false },
        { id: 'prep-4', text: '携带登记入场所需的身份证 (NRIC) 或使用 Singpass。', checked: false },
      ];
    case 'ta':
      return [
        { id: 'prep-2', text: 'நீங்கள் தற்போது உட்கொள்ளும் மருந்துகள் மற்றும் சப்ளிமெண்ட்ஸ்.', checked: false },
        { id: 'prep-3', text: 'உங்கள் மரபணு ஆலோசகரிடம் நீங்கள் கேட்க விரும்பும் கேள்விகள்.', checked: false },
        { id: 'prep-4', text: 'பதிவு செய்ய உங்கள் அடையாள அட்டை (NRIC) அல்லது Singpass.', checked: false },
      ];
    case 'en':
    default:
      return [
        { id: 'prep-2', text: 'Prepare a list of your current medications & supplement', checked: false },
        { id: 'prep-3', text: 'Review Learn section for resources and common questions', checked: false },
        { id: 'prep-4', text: 'Bring your NRIC or Singpass for identity verification', checked: false },
      ];
  }
};

// Localized educationalSections
export const getLocalizedEducationalSections = (lang: Language): EduSection[] => {
  switch (lang) {
    case 'ms':
      return [
        {
          id: 'what-is-fh',
          title: 'Apakah itu FH?',
          shortSummary: 'Apakah itu FH dan mengapa diagnosis awal sangat penting.',
          readingTime: 'Masa membaca: 3 minit',
          content: "Familial Hypercholesterolaemia (FH) adalah keadaan keturunan yang menghalang badan daripada membersihkan kolesterol LDL 'buruk' daripada darah. Berbeza dengan kolesterol tinggi biasa yang disebabkan oleh diet atau gaya hidup, tahap kolesterol FH adalah sangat tinggi sejak lahir, yang boleh merosakkan saluran darah secara senyap dan meningkatkan risiko penyakit jantung awal.",
          keyTakeaway: 'FH sepenuhnya genetik dan hadir sejak lahir, bermakna terapi perubatan hampir sentiasa diperlukan bersama tabiat sihat.',
          iconName: 'BookOpen',
          tags: ['kolesterol', 'genetik', 'kesihatan jantung'],
          subsections: [
            {
              title: 'BERAPA BIASAKAH IA BERLAKU?',
              text: 'FH menjejaskan kira-kira 1 daripada 250 rakyat Singapura. Kebanyakan orang dengan FH tidak menyedari mereka menghidapinya sehinggalah mereka menerima ujian genetik.'
            },
            {
              title: 'ADAKAH IA SALAH SAYA?',
              text: 'Tidak. FH sepenuhnya genetik. Ia diwarisi daripada ibu bapa dan tidak boleh diselesaikan melalui diet atau senaman sahaja—walaupun tabiat sihat masih penting.'
            }
          ]
        },
        {
          id: 'why-testing-matters',
          title: 'Melindungi Keluarga Anda',
          shortSummary: 'Bagaimana saringan lata memastikan orang tersayang selamat.',
          readingTime: 'Masa membaca: 3 minit',
          content: "Ujian genetik adalah standard emas untuk mengesahkan jika anda mempunyai FH. Menemui variasi gen khusus yang bertanggungjawab terhadap kolesterol tinggi membolehkan doktor menyesuaikan penjagaan pencegahan anda dan melindungi orang yang paling anda sayangi.",
          keyTakeaway: 'Satu ujian boleh melindungi kedua-dua diri anda dan orang yang anda sayangi.',
          iconName: 'Users',
          tags: ['keluarga', 'saringan lata', 'anak-anak'],
          subsections: [
            {
              title: 'MELINDUNGI KELUARGA ANDA (SARINGAN LATA)',
              text: 'Jika ujian anda positif, ibu bapa, adik-beradik, dan anak-anak anda mempunyai 50% peluang untuk mempunyai gen yang sama. Ujian membolehkan mereka disaring dan memulakan penjagaan pencegahan awal, menyelamatkan nyawa.'
            },
            {
              title: 'RAWATAN JITU',
              text: 'Mengesahkan genotip FH anda membantu doktor memilih dos yang tepat dan jenis ubat penurun lipid (seperti statin berpotensi tinggi).'
            }
          ]
        },
        {
          id: 'testing-guide',
          title: 'Panduan Ujian Anda',
          shortSummary: 'Langkah demi langkah daripada kaunseling ke keputusan anda.',
          readingTime: 'Masa membaca: 4 minit',
          content: "Perjalanan rujukan anda direka bentuk untuk sangat tersusun, menyokong, dan sepenuhnya pesakit luar. Tiada puasa diperlukan untuk ujian darah standard.",
          keyTakeaway: 'Setiap langkah direka untuk disesuaikan dengan lancar ke dalam jadual biasa anda.',
          iconName: 'ClipboardList',
          tags: ['ujian darah', 'kaunseling', 'apa yang dijangkakan'],
          steps: [
            { num: 1, title: 'Ketahui tentang FH', description: 'Baca panduan ringkas dan diperibadikan ini di aplikasi HealthHub anda.' },
            { num: 2, title: 'Tempah kaunseling', description: 'Jadualkan sesi anda dengan mudah terus di aplikasi ini dengan slot pilihan anda.' },
            { num: 3, title: 'Hadir ke sesi', description: 'Perbualan mesra selama 30 minit dengan kaunselor genetik untuk menyemak sejarah keluarga.' },
            { num: 4, title: 'Ujian darah standard', description: 'Pengambilan darah ringkas selama 10 minit di klinik. Tiada puasa atau persediaan diet diperlukan.' },
            { num: 5, title: 'Dapatkan keputusan dalam 4-6 minggu', description: 'Bertemu dengan pakar anda untuk menerima penjelasan yang jelas dan mudah difahami.' },
            { num: 6, title: 'Pelan pencegahan tersuai', description: 'Jika disahkan, mulakan terapi selamat dan bersubsidi yang mengembalikan risiko anda ke paras normal.' }
          ]
        },
        {
          id: 'costs-subsidies',
          title: 'Kos dan Subsidi',
          shortSummary: 'Kos yang anda bayar serta cara subsidi dan MediSave membantu.',
          readingTime: 'Masa membaca: 2.5 minit',
          content: "GovTech Singapore bekerjasama dengan Kementerian Kesihatan untuk memastikan penjagaan kesihatan kekal berpatutan. Ujian genetik untuk FH disubsidi dengan banyak.",
          keyTakeaway: 'Kos sendiri boleh dituntut melalui MediSave di bawah garis panduan pengurusan penyakit kronik.',
          iconName: 'Coins',
          tags: ['MediSave', 'CHAS', 'subsidi'],
          subsections: [
            {
              title: 'SUBSIDI MOH',
              text: 'Warganegara Singapura yang layak menerima subsidi 50% hingga 75% untuk kaunseling genetik dan ujian, bergantung pada tahap ujian kemampuan isi rumah mereka.'
            },
            {
              title: 'PENGGUNAAN MEDISAVE',
              text: 'Baki kos sendiri boleh ditolak menggunakan akaun MediSave anda di bawah garis panduan pengurusan penyakit kronik, meminimumkan pembayaran tunai segera.'
            },
            {
              title: 'MANFAAT KAD CHAS',
              text: 'Pemegang kad CHAS Biru, Jingga, dan Generasi Pioneer/Merdeka menerima subsidi yang dipertingkatkan, yang digunakan secara automatik semasa pembayaran.'
            }
          ]
        },
        {
          id: 'insurance-rights',
          title: 'Insurans & Hak Anda',
          shortSummary: 'Bagaimana Moratorium LIA melindungi anda.',
          readingTime: 'Masa membaca: 3 minit',
          content: "Kementerian Kesihatan Singapura dan Persatuan Insurans Hayat (LIA) mengekalkan Kod Pengguna yang ketat mengenai Ujian Genetik untuk melindungi data penjagaan kesihatan dan akses insurans anda.",
          keyTakeaway: 'Garis panduan kebangsaan melindungi sepenuhnya hak anda untuk mengambil ujian proaktif tanpa sebarang kesan polisi.',
          iconName: 'Shield',
          tags: ['insurans', 'privasi', 'moratorium LIA'],
          subsections: [
            {
              title: 'TIADA KESAN KEPADA PELAN SEDIA ADA',
              text: 'Polisi aktif sedia ada (seperti MediShield Life atau Pelan Integrated Shield) tidak boleh diubah, dibatalkan, atau ditetapkan semula harganya.'
            },
            {
              title: 'MORATORIUM LIA YANG KETAT',
              text: 'Syarikat insurans dilarang meminta anda mengambil ujian genetik, atau daripada meminta keputusan genetik untuk polisi hayat/kesihatan standard di bawah ambang yang tinggi.'
            }
          ]
        }
      ];
    case 'zh':
      return [
        {
          id: 'what-is-fh',
          title: '什么是 FH？',
          shortSummary: '了解什么是家族性高胆固醇血症，以及早期诊断的关键性。',
          readingTime: '3分钟阅读',
          content: "家族性高胆固醇血症 (FH) 是一种常染色体显性遗传病，导致患者体内的受体无法正常清除血液中的低密度脂蛋白（即“坏”胆固醇）。与因不良饮食或生活方式引起的普通高胆固醇不同，FH 患者体内的胆固醇水平自出生起便极高，会悄无声息地损伤血管，大幅增加早期罹患心脏病的风险。",
          keyTakeaway: 'FH 完全由遗传基因决定。这意味着除了健康生活习惯外，患者几乎都需要配合药物治疗。',
          iconName: 'BookOpen',
          tags: ['胆固醇', '基因科学', '心脏健康'],
          subsections: [
            {
              title: '患病率如何？',
              text: '在新加坡，约每250人中就有1人患有 FH。绝大多数 FH 患者在进行基因检测前都对自己的病情一无所知。'
            },
            {
              title: '这是我的错吗？',
              text: '不。FH 是100%遗传性疾病，由父母传给子女。单靠改善饮食或增加锻炼无法完全解决它——尽管健康的生活习惯依旧不可或缺。'
            }
          ]
        },
        {
          id: 'why-testing-matters',
          title: '保护您的至亲',
          shortSummary: '级联筛查如何守护您和您家人的生命安全。',
          readingTime: '3分钟阅读',
          content: "基因检测是确诊您是否患有 FH 的金标准。找出引起您高胆固醇的具体基因变异，能使医生为您量身定制最有效的预防治疗方案，从而保护您和您的挚爱。",
          keyTakeaway: '一次简单检测，可以守护您和您家人的双重健康。',
          iconName: 'Users',
          tags: ['家庭健康', '级联筛查', '关爱下一代'],
          subsections: [
            {
              title: '级联筛查（Cascade Screening）',
              text: '如果您确诊，您的父母、兄弟姐妹以及子女有50%的几率也携带有相同的 FH 致病基因。基因检测能帮助他们及早筛查，并在发生不测前采取有效的预防举措。'
            },
            {
              title: '精准医疗方案',
              text: '明确您的 FH 基因型，可以帮助医生精准选择最适合您的药剂用量和降脂药类型（如高效力他汀类药物）。'
            }
          ]
        },
        {
          id: 'testing-guide',
          title: '基因检测指南',
          shortSummary: '一步步了解从基因咨询到获取检测报告的全过程。',
          readingTime: '4分钟阅读',
          content: "您的转诊流程非常专业、人性化且完全在门诊进行。常规采血无需空腹，不影响日常安排。",
          keyTakeaway: '转诊旅程的每一步都是为您量身设计的，极其轻松便利。',
          iconName: 'ClipboardList',
          tags: ['采血化验', '医学咨询', '诊疗预期'],
          steps: [
            { num: 1, title: '了解 FH', description: '通过 HealthHub 应用程序阅读浅显易懂、专为您量身定制的科普指南。' },
            { num: 2, title: '预约咨询', description: '直接通过此应用轻松预约您心仪的基因咨询时段。' },
            { num: 3, title: '进行咨询', description: '与专业的基因咨询师进行30分钟亲切详实的谈话，评估家族病史。' },
            { num: 4, title: '常规采血', description: '在医院进行简单的10分钟采血，无需禁食空腹。' },
            { num: 5, title: '4-6周后获取报告', description: '再次与专科医生会面，听取全面、清晰且通俗易懂的报告解读。' },
            { num: 6, title: '定制预防方案', description: '一旦确诊，您将开启安全且享受政府高额津贴的预防性治疗，使心血管风险恢复正常。' }
          ]
        },
        {
          id: 'costs-subsidies',
          title: '费用与政府津贴',
          shortSummary: '详细了解自付费用、政府高额补贴以及如何使用 MediSave。',
          readingTime: '2.5分钟阅读',
          content: "新加坡卫生部 (MOH) 与 GovTech 紧密合作，确保所有国人都可轻松负担高品质医疗。FH 基因检测已纳入高额政府补贴。 ",
          keyTakeaway: '根据慢性疾病管理指南，您可以使用 MediSave（保健储蓄）报销绝大多数的自付费用。',
          iconName: 'Coins',
          tags: ['MediSave储蓄', 'CHAS津贴', '政府补贴'],
          subsections: [
            {
              title: '新加坡卫生部 (MOH) 补贴',
              text: '符合资格的新加坡公民在接受基因咨询和检测时，可根据家庭收入调查级别，获得 50% 至 75% 的高额政府直接津贴。'
            },
            {
              title: '使用 MediSave 保健储蓄',
              text: '剩余的个人自付费用，可在慢性疾病管理计划（CDMP）下通过您的 MediSave 账户予以扣除，最大程度降低现金支出压力。'
            },
            {
              title: 'CHAS 卡尊享福利',
              text: 'CHAS蓝色卡、橙色卡，以及建国一代或立国一代卡持有者可直接享有更高的专属额外补贴，该费用在结算时会自动进行抵扣。'
            }
          ]
        },
        {
          id: 'insurance-rights',
          title: '商业保险与您的合法权益',
          shortSummary: '深入了解人寿保险公会 (LIA) 暂缓执行令如何守护您。',
          readingTime: '3分钟阅读',
          content: "新加坡卫生部与人寿保险公会联合颁布并坚决执行严格的《基因检测消费者守则》，以全力保护您的个人健康隐私和未来的商业投保权益。",
          keyTakeaway: '国家专属守则完全保障您的权益，您可安心检测，毫无后顾之忧。',
          iconName: 'Shield',
          tags: ['商业投保', '隐私权保护', 'LIA暂缓执行令'],
          subsections: [
            {
              title: '不影响已生效的保单',
              text: '任何您已经购买且正在生效的保单（如 MediShield Life 终身健保或 Integrated Shield Plans 综合健保双全计划）绝不会受到影响，保险公司无权将其终止、取消或上调保费。'
            },
            {
              title: '严苛的 LIA 暂缓执行令',
              text: '保险公司严禁强制要求您进行基因检测；在申请常规人寿或健康保险时（只要保额不超过法定高额限度），保险商也严禁向您索取基因检测结果。'
            }
          ]
        }
      ];
    case 'ta':
      return [
        {
          id: 'what-is-fh',
          title: 'FH என்றால் என்ன?',
          shortSummary: 'FH என்றால் என்ன மற்றும் ஆரம்ப கட்டத்திலேயே கண்டறிவதன் முக்கியத்துவம்.',
          readingTime: '3 நிமிட வாசிப்பு',
          content: "குடும்பவழி ஹைபர்கொலஸ்டிரோலேமியா (FH) என்பது உடலிலிருந்து 'கெட்ட' எல்.டி.எல் கொழுப்பை அகற்றுவதைத் தடுக்கும் ஒரு பரம்பரை நிலையாகும். உணவு அல்லது வாழ்க்கை முறையால் ஏற்படும் சாதாரண கொலஸ்ட்ராலை விட, FH கொலஸ்ட்ரால் பிறப்பிலிருந்தே மிக அதிகமாக உள்ளது, இது இரத்த நாளங்களை சேதப்படுத்தி, இதய நோய் அபாயத்தை உருவாக்குகிறது.",
          keyTakeaway: 'FH முற்றிலும் மரபணு சார்ந்தது, எனவே ஆரோக்கியமான பழக்கவழக்கங்களுடன் மருத்துவ சிகிச்சையும் அவசியமாகும்.',
          iconName: 'BookOpen',
          tags: ['கொலஸ்ட்ரால்', 'மரபியல்', 'இதய ஆரோக்கியம்'],
          subsections: [
            {
              title: 'இது எவ்வளவு பொதுவானது?',
              text: 'சிங்கப்பூரியர்களில் 250 பேரில் ஒருவரை FH பாதிக்கிறது. மரபணு சோதனை செய்யும் வரை தங்களுக்கு இந்த நோய் இருப்பது பெரும்பாலான மக்களுக்குத் தெரியாது.'
            },
            {
              title: 'இது என் தவறா?',
              text: 'இல்லை. FH முற்றிலும் மரபணு சார்ந்தது. இது பெற்றோரிடமிருந்து பெறப்படுகிறது, உணவு அல்லது உடற்பயிற்சியால் மட்டும் இதைக் குணப்படுத்த முடியாது.'
            }
          ]
        },
        {
          id: 'why-testing-matters',
          title: 'உங்கள் குடும்பத்தைப் பாதுகாத்தல்',
          shortSummary: 'மரபணு சோதனை எவ்வாறு உங்கள் அன்புக்குரியவர்களைப் பாதுகாக்கிறது.',
          readingTime: '3 நிமிட வாசிப்பு',
          content: "உங்களுக்கு FH உள்ளதா என்பதை உறுதிப்படுத்த மரபணு சோதனை சிறந்த வழியாகும். குறிப்பிட்ட மரபணு மாறுபாட்டைக் கண்டறிவது, மருத்துவர்கள் உங்களது தடுப்பு சிகிச்சையைத் தனிப்பயனாக்கவும், உங்கள் அன்புக்குரியவர்களைப் பாதுகாக்கவும் உதவுகிறது.",
          keyTakeaway: 'ஒரு சோதனை உங்களையும் உங்கள் அன்பானவர்களையும் பாதுகாக்கும்.',
          iconName: 'Users',
          tags: ['குடும்பம்', 'மரபணு சோதனை', 'குழந்தைகள்'],
          subsections: [
            {
              title: 'குடும்பத்தைப் பாதுகாத்தல் (Cascade Screening)',
              text: 'உங்களுக்குப் பாதிப்பு இருந்தால், உங்கள் பெற்றோர், உடன்பிறந்தோர் மற்றும் குழந்தைகளுக்கு அதே மரபணு இருக்க 50% வாய்ப்பு உள்ளது. சோதனை மூலம் அவர்களைக் கண்டறிந்து ஆரம்பத்திலேயே சிகிச்சை அளிக்கலாம்.'
            },
            {
              title: 'துல்லியமான சிகிச்சை',
              text: 'உங்கள் FH மரபணு வகையை உறுதிப்படுத்துவது, மருத்துவர் சரியான அளவு மற்றும் மருந்து வகையைத் தேர்வு செய்ய உதவுகிறது.'
            }
          ]
        },
        {
          id: 'testing-guide',
          title: 'உங்கள் சோதனை வழிகாட்டி',
          shortSummary: 'ஆலோசனை முதல் முடிவுகள் வரையிலான படிப்படியான வழிகாட்டி.',
          readingTime: '4 நிமிட வாசிப்பு',
          content: "உங்கள் மருத்துவப் பயணம் மிகவும் ஒழுங்கமைக்கப்பட்டதாகவும், ஆதரவானதாகவும் வடிவமைக்கப்பட்டுள்ளது. இரத்தப் பரிசோதனைக்கு உண்ணாவிரதம் தேவையில்லை.",
          keyTakeaway: 'ஒவ்வொரு படியும் உங்கள் சாதாரண அட்டவணையுடன் எளிதாகப் பொருந்தும் வகையில் வடிவமைக்கப்பட்டுள்ளது.',
          iconName: 'ClipboardList',
          tags: ['இரத்த பரிசோதனை', 'ஆலோசனை', 'எதிர்பார்ப்பு'],
          steps: [
            { num: 1, title: 'FH பற்றி அறியவும்', description: 'உங்களது HealthHub செயலியில் தனிப்பயனாக்கப்பட்ட வழிகாட்டிகளைப் படிக்கவும்.' },
            { num: 2, title: 'ஆலோசனையை முன்பதிவு செய்ய', description: 'விரும்பிய நேரத்தைத் தேர்வுசெய்து இந்த செயலியில் எளிதாக முன்பதிவு செய்யவும்.' },
            { num: 3, title: 'ஆலோசனை பெறவும்', description: 'மரபணு ஆலோசகருடன் குடும்ப வரலாறு குறித்து 30 நிமிட உரையாடல்.' },
            { num: 4, title: 'இரத்தப் பரிசோதனை', description: 'மருத்துவமனையில் 10 நிமிட எளிய இரத்தப் பரிசோதனை. உண்ணாவிரதம் தேவையில்லை.' },
            { num: 5, title: '4-6 வாரங்களில் முடிவுகள்', description: 'முடிவுகளைப் பெற உங்கள் மருத்துவரைச் சந்தித்து எளிய விளக்கத்தைப் பெறவும்.' },
            { num: 6, title: 'தனிப்பயனாக்கப்பட்ட சிகிச்சை', description: 'உறுதிசெய்யப்பட்டால், உங்களது ஆரோக்கியத்தை சீராக்கும் மானியம் பெற்ற பாதுகாப்பான சிகிச்சையைத் தொடங்கவும்.' }
          ]
        },
        {
          id: 'costs-subsidies',
          title: 'கட்டணம் மற்றும் மானியங்கள்',
          shortSummary: 'நீங்கள் செலுத்தும் கட்டணம் மற்றும் அரசு மானியம், MediSave எவ்வாறு உதவுகிறது.',
          readingTime: '2.5 நிமிட வாசிப்பு',
          content: "சுகாதாரச் சேவைகள் மலிவு விலையில் கிடைப்பதை உறுதி செய்ய சிங்கப்பூர் சுகாதார அமைச்சகம் (MOH) மானியங்களை வழங்குகிறது.",
          keyTakeaway: 'மீதமுள்ள கட்டணத்தை நாள்பட்ட நோய் மேலாண்மை வழிகாட்டுதலின் கீழ் MediSave மூலம் செலுத்தலாம்.',
          iconName: 'Coins',
          tags: ['MediSave', 'CHAS', 'மானியங்கள்'],
          subsections: [
            {
              title: 'MOH மானியங்கள்',
              text: 'தகுதியான சிங்கப்பூர் குடிமக்கள் தங்களது குடும்ப வருமான வரம்பிற்கு ஏற்ப 50% முதல் 75% வரை மானியம் பெறலாம்.'
            },
            {
              title: 'MEDISAVE பயன்பாடு',
              text: 'மீதமுள்ள கட்டணத்தை உங்கள் MediSave கணக்கிலிருந்து செலுத்தலாம், இதனால் உடனடி பணத் தொகை குறைகிறது.'
            },
            {
              title: 'CHAS அட்டை நன்மைகள்',
              text: 'CHAS ப்ளூ, ஆரஞ்சு மற்றும் முன்னோடித் தலைமுறை அட்டைதாரர்களுக்கு கூடுதல் மானியங்கள் தானாகவே பயன்படுத்தப்படும்.'
            }
          ]
        },
        {
          id: 'insurance-rights',
          title: 'காப்பீடு & உங்கள் உரிமைகள்',
          shortSummary: 'LIA மொராட்டோரியம் எவ்வாறு உங்களைப் பாதுகாக்கிறது.',
          readingTime: '3 நிமிட வாசிப்பு',
          content: "சிங்கப்பூர் சுகாதார அமைச்சகம் மற்றும் காப்பீட்டு சங்கம் (LIA) உங்கள் தரவு மற்றும் காப்பீட்டைப் பாதுகாக்க கடுமையான விதிகளைப் பின்பற்றுகின்றன.",
          keyTakeaway: 'தேசிய வழிகாட்டுதல்கள் உங்களது காப்பீட்டைப் பாதிக்காமல் சோதனை செய்ய உங்களை முழுமையாகப் பாதுகாக்கின்றன.',
          iconName: 'Shield',
          tags: ['காப்பீடு', 'தனியுரிமை', 'LIA மொராட்டோரியம்'],
          subsections: [
            {
              title: 'தற்போதுள்ள காப்பீடுகளில் பாதிப்பு இல்லை',
              text: 'உங்களிடம் ஏற்கனவே உள்ள காப்பீடுகளை (MediShield Life போன்றவை) காப்பீட்டு நிறுவனங்கள் ரத்து செய்யவோ அல்லது பிரீமியத்தை உயர்த்தவோ முடியாது.'
            },
            {
              title: 'கடுமையான LIA கட்டுப்பாடு',
              text: 'உங்களை மரபணு சோதனை செய்ய காப்பீட்டு நிறுவனங்கள் கட்டாயப்படுத்தக் கூடாது, அல்லது சாதாரண காப்பீடுகளுக்கு அதன் முடிவுகளைக் கேட்கக் கூடாது.'
            }
          ]
        }
      ];
    case 'en':
    default:
      return educationalSections;
  }
};

// Localized FAQs
export const getLocalizedFaqs = (lang: Language): FAQItem[] => {
  switch (lang) {
    case 'ms':
      return [
        {
          question: 'Adakah saya perlu berpuasa sebelum janji temu kaunseling genetik atau ujian darah?',
          answer: 'Tidak. Kaunseling genetik adalah perbincangan, dan ujian darah FH tidak memerlukan sebarang puasa. Anda boleh makan, minum, dan mengambil ubat biasa anda seperti biasa sebelum hadir.',
          category: 'testing'
        },
        {
          question: 'Berapakah kos ujian darah genetik selepas subsidi?',
          answer: 'Bagi Warganegara Singapura yang layak mendapat subsidi MOH (seperti pemegang CHAS Biru), kos sendiri yang tinggal biasanya adalah antara S$15 hingga S$45 sahaja. Baki ini juga boleh dibayar sepenuhnya menggunakan MediSave.',
          category: 'cost'
        },
        {
          question: 'Adakah keputusan ujian genetik saya akan menjejaskan insurans hayat atau perubatan sedia ada?',
          answer: 'Sama sekali tidak. Di bawah Moratorium Persatuan Insurans Hayat (LIA) Singapura yang ketat, semua insurans perubatan sedia ada dan insurans hayat di bawah had tertentu tidak boleh diubah, dibatalkan, atau dinaikkan harga berdasarkan keputusan ujian genetik sukarela.',
          category: 'insurance'
        },
        {
          question: 'Sekiranya keputusan saya adalah positif, adakah anak-anak atau ahli keluarga saya perlu diuji juga?',
          answer: 'Ya, ini dipanggil saringan lata (cascade screening). Oleh kerana FH diwarisi, ahli keluarga terdekat anda (ibu bapa, adik-beradik, dan anak-anak) mempunyai peluang 50% untuk mempunyai keadaan yang sama. Kami akan membimbing anda tentang cara membantu mereka mendapatkan ujian bersubsidi tinggi dengan selamat.',
          category: 'family'
        },
        {
          question: 'Berapa lamakah masa yang diambil untuk mendapatkan keputusan ujian darah genetik?',
          answer: 'Sampel dihantar ke makmal khusus genetik klinikal. Keputusan penuh biasanya tersedia dalam tempoh 4 hingga 6 minggu. Anda akan dipanggil untuk sesi susulan bagi menerangkan hasil keputusan secara terperinci.',
          category: 'testing'
        }
      ];
    case 'zh':
      return [
        {
          question: '基因咨询或采血化验前需要禁食空腹吗？',
          answer: '完全不需要。基因咨询是以谈话和评估为主，而针对 FH 的基因采血检查也不需要禁食。您可以照常饮食、喝水，并照常服用您平时所需的任何日常药物。',
          category: 'testing'
        },
        {
          question: '扣除政府津贴后，基因检测的实际个人自付费用是多少？',
          answer: '符合新加坡卫生部补贴资格的公民（例如 CHAS 蓝色卡持有者），在享受高达 75% 的政府直接直接津贴后，个人自付费用通常仅在 15 至 45 新元之间。此外，剩余的全部账单均可直接使用您的 MediSave 账户予以支付，无需支付现金。',
          category: 'cost'
        },
        {
          question: '基因检测结果会影响我已有的商业人寿险或重疾险保单吗？',
          answer: '绝对不会。根据新加坡人寿保险公会（LIA）颁布的严格暂缓执行令，您已购买并生效的商业医疗险、重疾险和常规人寿保单绝不会因为您自愿进行的基因检测而受到任何惩罚、修改、取消或保费上调。',
          category: 'insurance'
        },
        {
          question: '如果检测结果呈阳性，我的子女或兄弟姐妹也必须进行检测吗？',
          answer: '非常建议他们进行检测。这在医学上被称为级联筛查（Cascade Screening）。由于 FH 是强遗传病，您的直系亲属（父母、兄弟姐妹及子女）有高达 50% 的几率携带有相同的突变基因。我们专业的咨询团队会指引您如何帮助家人安全、便捷地申请相同的高额津贴筛查。',
          category: 'family'
        },
        {
          question: '采血化验后需要多久才能拿到基因报告？',
          answer: '采血样本会被送往国家临床基因专科实验室进行精密的定序分析。完整的基因检测报告通常需要 4 至 6 周的时间出炉。报告出来后，主治专科医生会为您安排复诊，为您进行通俗且详实的面对面解读。',
          category: 'testing'
        }
      ];
    case 'ta':
      return [
        {
          question: 'மரபணு ஆலோசனை அல்லது இரத்த பரிசோதனைக்கு முன்பு நான் உண்ணாவிரதம் இருக்க வேண்டுமா?',
          answer: 'இல்லை. மரபணு ஆலோசனை என்பது ஒரு கலந்துரையாடல், மேலும் FH இரத்த பரிசோதனைக்கு உண்ணாவிரதம் தேவையில்லை. நீங்கள் சாதாரணமாக சாப்பிட்டு, உங்கள் வழக்கமான மருந்துகளை உட்கொள்ளலாம்.',
          category: 'testing'
        },
        {
          question: 'மானியங்களுக்குப் பிறகு மரபணு பரிசோதனைக்கான கட்டணம் எவ்வளவு இருக்கும்?',
          answer: 'MOH மானியம் பெற தகுதியுள்ள சிங்கப்பூர் குடிமக்களுக்கு (CHAS ப்ளூ அட்டைதாரர்கள் போன்றவை), மீதமுள்ள கட்டணம் பொதுவாக S$15 முதல் S$45 வரை மட்டுமே இருக்கும். இதை உங்கள் MediSave கணக்கைப் பயன்படுத்தி முழுமையாக செலுத்தலாம்.',
          category: 'cost'
        },
        {
          question: 'எனது மரபணு சோதனை முடிவுகள் தற்போதுள்ள காப்பீடுகளைப் பாதிக்குமா?',
          answer: 'கண்டிப்பாகப் பாதிக்காது. சிங்கப்பூர் காப்பீட்டு சங்கத்தின் (LIA) கடுமையான விதிகளின்படி, தற்போதுள்ள காப்பீடுகளை காப்பீட்டு நிறுவனங்கள் ரத்து செய்யவோ அல்லது பிரீமியத்தை உயர்த்தவோ முடியாது.',
          category: 'insurance'
        },
        {
          question: 'முடிவு சாதகமாக இருந்தால், எனது குழந்தைகள் அல்லது குடும்பத்தினரும் சோதனை செய்ய வேண்டுமா?',
          answer: 'ஆம், இது Cascade Screening என்று அழைக்கப்படுகிறது. FH மரபுவழியாக பரவுவதால், உங்கள் பெற்றோர், உடன்பிறந்தோர் மற்றும் குழந்தைகளுக்கு 50% வாய்ப்பு உள்ளது. அவர்களுக்கு மானிய விலையில் சோதனை செய்ய நாங்கள் உங்களுக்கு வழிகாட்டுவோம்.',
          category: 'family'
        },
        {
          question: 'மரபணு சோதனை முடிவுகள் கிடைக்க எவ்வளவு காலம் ஆகும்?',
          answer: 'மரபணு சோதனை முடிவுகள் கிடைக்க பொதுவாக 4 முதல் 6 வாரங்கள் வரை ஆகும். முடிவுகள் வந்தவுடன், விரிவான விளக்கத்தைப் பெற உங்களை மீண்டும் சந்திப்பிற்கு அழைப்போம்.',
          category: 'testing'
        }
      ];
    case 'en':
    default:
      return [
        {
          question: 'Do I need to fast before the genetic counselling appointment or blood draw?',
          answer: 'No. Genetic counselling is a discussion, and the FH genetic blood test does not require any fasting. You can eat, drink, and take your regular daily medications normally beforehand.',
          category: 'testing'
        },
        {
          question: 'How much does the genetic test actually cost after subsidies?',
          answer: 'For Singapore Citizens eligible for MOH subsidies (such as CHAS Blue cardholders), the remaining out-of-pocket cost is typically between S$15 to S$45. The entire remaining balance can be fully paid using your MediSave account, requiring zero cash up-front.',
          category: 'cost'
        },
        {
          question: 'Will my genetic test results affect my existing life or health insurance policies?',
          answer: 'Absolutely not. Under Singapore\'s strict Life Insurance Association (LIA) Moratorium, all existing active health and life insurance policies below high thresholds can never be modified, canceled, or re-priced based on a voluntary clinical genetic test.',
          category: 'insurance'
        },
        {
          question: 'If my test is positive, do my children or siblings need to be tested too?',
          answer: 'Yes, this is called cascade screening. Because FH is highly hereditary, your first-degree relatives (parents, siblings, and children) have a 50% chance of sharing the same variation. We will guide you on how to help them access highly subsidized testing safely.',
          category: 'family'
        },
        {
          question: 'How long does it take to receive the clinical genetic testing results?',
          answer: 'Samples are processed in a clinical genetics lab. Complete results are typically returned in 4 to 6 weeks. You will be scheduled for a follow-up consultation where your clinician will explain the findings in detail.',
          category: 'testing'
        }
      ];
  }
};
